
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/app
      - /app/tmp # Це допоможе уникнути кешування тимчасових файлів
    # develop:
    #   watch:
    #     - path: .
    #       action: sync
    #       target: /app
volumes:
  pgdata:
