// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldDiscountPercentage holds the string denoting the discount_percentage field in the database.
	FieldDiscountPercentage = "discount_percentage"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldStock holds the string denoting the stock field in the database.
	FieldStock = "stock"
	// FieldBrand holds the string denoting the brand field in the database.
	FieldBrand = "brand"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldWarrantyInformation holds the string denoting the warranty_information field in the database.
	FieldWarrantyInformation = "warranty_information"
	// FieldShippingInformation holds the string denoting the shipping_information field in the database.
	FieldShippingInformation = "shipping_information"
	// FieldAvailabilityStatus holds the string denoting the availability_status field in the database.
	FieldAvailabilityStatus = "availability_status"
	// FieldReturnPolicy holds the string denoting the return_policy field in the database.
	FieldReturnPolicy = "return_policy"
	// FieldMinimumOrderQuantity holds the string denoting the minimum_order_quantity field in the database.
	FieldMinimumOrderQuantity = "minimum_order_quantity"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldBarcode holds the string denoting the barcode field in the database.
	FieldBarcode = "barcode"
	// FieldQrCode holds the string denoting the qr_code field in the database.
	FieldQrCode = "qr_code"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldImages holds the string denoting the images field in the database.
	FieldImages = "images"
	// FieldDimensions holds the string denoting the dimensions field in the database.
	FieldDimensions = "dimensions"
	// FieldReviews holds the string denoting the reviews field in the database.
	FieldReviews = "reviews"
	// EdgeOrderProducts holds the string denoting the order_products edge name in mutations.
	EdgeOrderProducts = "order_products"
	// Table holds the table name of the product in the database.
	Table = "products"
	// OrderProductsTable is the table that holds the order_products relation/edge.
	OrderProductsTable = "order_products"
	// OrderProductsInverseTable is the table name for the OrderProducts entity.
	// It exists in this package in order to avoid circular dependency with the "orderproducts" package.
	OrderProductsInverseTable = "order_products"
	// OrderProductsColumn is the table column denoting the order_products relation/edge.
	OrderProductsColumn = "product_order_products"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldCategory,
	FieldPrice,
	FieldDiscountPercentage,
	FieldRating,
	FieldStock,
	FieldBrand,
	FieldSku,
	FieldWeight,
	FieldWarrantyInformation,
	FieldShippingInformation,
	FieldAvailabilityStatus,
	FieldReturnPolicy,
	FieldMinimumOrderQuantity,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldBarcode,
	FieldQrCode,
	FieldThumbnail,
	FieldTags,
	FieldImages,
	FieldDimensions,
	FieldReviews,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// BrandValidator is a validator for the "brand" field. It is called by the builders before save.
	BrandValidator func(string) error
	// SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	SkuValidator func(string) error
	// WarrantyInformationValidator is a validator for the "warranty_information" field. It is called by the builders before save.
	WarrantyInformationValidator func(string) error
	// ShippingInformationValidator is a validator for the "shipping_information" field. It is called by the builders before save.
	ShippingInformationValidator func(string) error
	// AvailabilityStatusValidator is a validator for the "availability_status" field. It is called by the builders before save.
	AvailabilityStatusValidator func(string) error
	// ReturnPolicyValidator is a validator for the "return_policy" field. It is called by the builders before save.
	ReturnPolicyValidator func(string) error
	// BarcodeValidator is a validator for the "barcode" field. It is called by the builders before save.
	BarcodeValidator func(string) error
	// QrCodeValidator is a validator for the "qr_code" field. It is called by the builders before save.
	QrCodeValidator func(string) error
	// ThumbnailValidator is a validator for the "thumbnail" field. It is called by the builders before save.
	ThumbnailValidator func(string) error
)

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByDiscountPercentage orders the results by the discount_percentage field.
func ByDiscountPercentage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountPercentage, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByStock orders the results by the stock field.
func ByStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStock, opts...).ToFunc()
}

// ByBrand orders the results by the brand field.
func ByBrand(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrand, opts...).ToFunc()
}

// BySku orders the results by the sku field.
func BySku(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSku, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByWarrantyInformation orders the results by the warranty_information field.
func ByWarrantyInformation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarrantyInformation, opts...).ToFunc()
}

// ByShippingInformation orders the results by the shipping_information field.
func ByShippingInformation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShippingInformation, opts...).ToFunc()
}

// ByAvailabilityStatus orders the results by the availability_status field.
func ByAvailabilityStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailabilityStatus, opts...).ToFunc()
}

// ByReturnPolicy orders the results by the return_policy field.
func ByReturnPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnPolicy, opts...).ToFunc()
}

// ByMinimumOrderQuantity orders the results by the minimum_order_quantity field.
func ByMinimumOrderQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinimumOrderQuantity, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBarcode orders the results by the barcode field.
func ByBarcode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarcode, opts...).ToFunc()
}

// ByQrCode orders the results by the qr_code field.
func ByQrCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQrCode, opts...).ToFunc()
}

// ByThumbnail orders the results by the thumbnail field.
func ByThumbnail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnail, opts...).ToFunc()
}

// ByOrderProductsCount orders the results by order_products count.
func ByOrderProductsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrderProductsStep(), opts...)
	}
}

// ByOrderProducts orders the results by order_products terms.
func ByOrderProducts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderProductsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrderProductsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderProductsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrderProductsTable, OrderProductsColumn),
	)
}
