// Code generated by ent, DO NOT EDIT.

package product

import (
	"golang-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDescription, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCategory, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldPrice, v))
}

// DiscountPercentage applies equality check predicate on the "discount_percentage" field. It's identical to DiscountPercentageEQ.
func DiscountPercentage(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDiscountPercentage, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldRating, v))
}

// Stock applies equality check predicate on the "stock" field. It's identical to StockEQ.
func Stock(v int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldStock, v))
}

// Brand applies equality check predicate on the "brand" field. It's identical to BrandEQ.
func Brand(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBrand, v))
}

// Sku applies equality check predicate on the "sku" field. It's identical to SkuEQ.
func Sku(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSku, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldWeight, v))
}

// WarrantyInformation applies equality check predicate on the "warranty_information" field. It's identical to WarrantyInformationEQ.
func WarrantyInformation(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldWarrantyInformation, v))
}

// ShippingInformation applies equality check predicate on the "shipping_information" field. It's identical to ShippingInformationEQ.
func ShippingInformation(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldShippingInformation, v))
}

// AvailabilityStatus applies equality check predicate on the "availability_status" field. It's identical to AvailabilityStatusEQ.
func AvailabilityStatus(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldAvailabilityStatus, v))
}

// ReturnPolicy applies equality check predicate on the "return_policy" field. It's identical to ReturnPolicyEQ.
func ReturnPolicy(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldReturnPolicy, v))
}

// MinimumOrderQuantity applies equality check predicate on the "minimum_order_quantity" field. It's identical to MinimumOrderQuantityEQ.
func MinimumOrderQuantity(v int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldMinimumOrderQuantity, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldUpdatedAt, v))
}

// Barcode applies equality check predicate on the "barcode" field. It's identical to BarcodeEQ.
func Barcode(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBarcode, v))
}

// QrCode applies equality check predicate on the "qr_code" field. It's identical to QrCodeEQ.
func QrCode(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldQrCode, v))
}

// Thumbnail applies equality check predicate on the "thumbnail" field. It's identical to ThumbnailEQ.
func Thumbnail(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldThumbnail, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldDescription, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldCategory, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldPrice, v))
}

// DiscountPercentageEQ applies the EQ predicate on the "discount_percentage" field.
func DiscountPercentageEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldDiscountPercentage, v))
}

// DiscountPercentageNEQ applies the NEQ predicate on the "discount_percentage" field.
func DiscountPercentageNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldDiscountPercentage, v))
}

// DiscountPercentageIn applies the In predicate on the "discount_percentage" field.
func DiscountPercentageIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldDiscountPercentage, vs...))
}

// DiscountPercentageNotIn applies the NotIn predicate on the "discount_percentage" field.
func DiscountPercentageNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldDiscountPercentage, vs...))
}

// DiscountPercentageGT applies the GT predicate on the "discount_percentage" field.
func DiscountPercentageGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldDiscountPercentage, v))
}

// DiscountPercentageGTE applies the GTE predicate on the "discount_percentage" field.
func DiscountPercentageGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldDiscountPercentage, v))
}

// DiscountPercentageLT applies the LT predicate on the "discount_percentage" field.
func DiscountPercentageLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldDiscountPercentage, v))
}

// DiscountPercentageLTE applies the LTE predicate on the "discount_percentage" field.
func DiscountPercentageLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldDiscountPercentage, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldRating, v))
}

// StockEQ applies the EQ predicate on the "stock" field.
func StockEQ(v int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldStock, v))
}

// StockNEQ applies the NEQ predicate on the "stock" field.
func StockNEQ(v int) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldStock, v))
}

// StockIn applies the In predicate on the "stock" field.
func StockIn(vs ...int) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldStock, vs...))
}

// StockNotIn applies the NotIn predicate on the "stock" field.
func StockNotIn(vs ...int) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldStock, vs...))
}

// StockGT applies the GT predicate on the "stock" field.
func StockGT(v int) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldStock, v))
}

// StockGTE applies the GTE predicate on the "stock" field.
func StockGTE(v int) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldStock, v))
}

// StockLT applies the LT predicate on the "stock" field.
func StockLT(v int) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldStock, v))
}

// StockLTE applies the LTE predicate on the "stock" field.
func StockLTE(v int) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldStock, v))
}

// BrandEQ applies the EQ predicate on the "brand" field.
func BrandEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBrand, v))
}

// BrandNEQ applies the NEQ predicate on the "brand" field.
func BrandNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldBrand, v))
}

// BrandIn applies the In predicate on the "brand" field.
func BrandIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldBrand, vs...))
}

// BrandNotIn applies the NotIn predicate on the "brand" field.
func BrandNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldBrand, vs...))
}

// BrandGT applies the GT predicate on the "brand" field.
func BrandGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldBrand, v))
}

// BrandGTE applies the GTE predicate on the "brand" field.
func BrandGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldBrand, v))
}

// BrandLT applies the LT predicate on the "brand" field.
func BrandLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldBrand, v))
}

// BrandLTE applies the LTE predicate on the "brand" field.
func BrandLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldBrand, v))
}

// BrandContains applies the Contains predicate on the "brand" field.
func BrandContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldBrand, v))
}

// BrandHasPrefix applies the HasPrefix predicate on the "brand" field.
func BrandHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldBrand, v))
}

// BrandHasSuffix applies the HasSuffix predicate on the "brand" field.
func BrandHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldBrand, v))
}

// BrandEqualFold applies the EqualFold predicate on the "brand" field.
func BrandEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldBrand, v))
}

// BrandContainsFold applies the ContainsFold predicate on the "brand" field.
func BrandContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldBrand, v))
}

// SkuEQ applies the EQ predicate on the "sku" field.
func SkuEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldSku, v))
}

// SkuNEQ applies the NEQ predicate on the "sku" field.
func SkuNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldSku, v))
}

// SkuIn applies the In predicate on the "sku" field.
func SkuIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldSku, vs...))
}

// SkuNotIn applies the NotIn predicate on the "sku" field.
func SkuNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldSku, vs...))
}

// SkuGT applies the GT predicate on the "sku" field.
func SkuGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldSku, v))
}

// SkuGTE applies the GTE predicate on the "sku" field.
func SkuGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldSku, v))
}

// SkuLT applies the LT predicate on the "sku" field.
func SkuLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldSku, v))
}

// SkuLTE applies the LTE predicate on the "sku" field.
func SkuLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldSku, v))
}

// SkuContains applies the Contains predicate on the "sku" field.
func SkuContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldSku, v))
}

// SkuHasPrefix applies the HasPrefix predicate on the "sku" field.
func SkuHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldSku, v))
}

// SkuHasSuffix applies the HasSuffix predicate on the "sku" field.
func SkuHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldSku, v))
}

// SkuEqualFold applies the EqualFold predicate on the "sku" field.
func SkuEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldSku, v))
}

// SkuContainsFold applies the ContainsFold predicate on the "sku" field.
func SkuContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldSku, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v float64) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...float64) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v float64) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v float64) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v float64) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldWeight, v))
}

// WarrantyInformationEQ applies the EQ predicate on the "warranty_information" field.
func WarrantyInformationEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldWarrantyInformation, v))
}

// WarrantyInformationNEQ applies the NEQ predicate on the "warranty_information" field.
func WarrantyInformationNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldWarrantyInformation, v))
}

// WarrantyInformationIn applies the In predicate on the "warranty_information" field.
func WarrantyInformationIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldWarrantyInformation, vs...))
}

// WarrantyInformationNotIn applies the NotIn predicate on the "warranty_information" field.
func WarrantyInformationNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldWarrantyInformation, vs...))
}

// WarrantyInformationGT applies the GT predicate on the "warranty_information" field.
func WarrantyInformationGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldWarrantyInformation, v))
}

// WarrantyInformationGTE applies the GTE predicate on the "warranty_information" field.
func WarrantyInformationGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldWarrantyInformation, v))
}

// WarrantyInformationLT applies the LT predicate on the "warranty_information" field.
func WarrantyInformationLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldWarrantyInformation, v))
}

// WarrantyInformationLTE applies the LTE predicate on the "warranty_information" field.
func WarrantyInformationLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldWarrantyInformation, v))
}

// WarrantyInformationContains applies the Contains predicate on the "warranty_information" field.
func WarrantyInformationContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldWarrantyInformation, v))
}

// WarrantyInformationHasPrefix applies the HasPrefix predicate on the "warranty_information" field.
func WarrantyInformationHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldWarrantyInformation, v))
}

// WarrantyInformationHasSuffix applies the HasSuffix predicate on the "warranty_information" field.
func WarrantyInformationHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldWarrantyInformation, v))
}

// WarrantyInformationEqualFold applies the EqualFold predicate on the "warranty_information" field.
func WarrantyInformationEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldWarrantyInformation, v))
}

// WarrantyInformationContainsFold applies the ContainsFold predicate on the "warranty_information" field.
func WarrantyInformationContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldWarrantyInformation, v))
}

// ShippingInformationEQ applies the EQ predicate on the "shipping_information" field.
func ShippingInformationEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldShippingInformation, v))
}

// ShippingInformationNEQ applies the NEQ predicate on the "shipping_information" field.
func ShippingInformationNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldShippingInformation, v))
}

// ShippingInformationIn applies the In predicate on the "shipping_information" field.
func ShippingInformationIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldShippingInformation, vs...))
}

// ShippingInformationNotIn applies the NotIn predicate on the "shipping_information" field.
func ShippingInformationNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldShippingInformation, vs...))
}

// ShippingInformationGT applies the GT predicate on the "shipping_information" field.
func ShippingInformationGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldShippingInformation, v))
}

// ShippingInformationGTE applies the GTE predicate on the "shipping_information" field.
func ShippingInformationGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldShippingInformation, v))
}

// ShippingInformationLT applies the LT predicate on the "shipping_information" field.
func ShippingInformationLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldShippingInformation, v))
}

// ShippingInformationLTE applies the LTE predicate on the "shipping_information" field.
func ShippingInformationLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldShippingInformation, v))
}

// ShippingInformationContains applies the Contains predicate on the "shipping_information" field.
func ShippingInformationContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldShippingInformation, v))
}

// ShippingInformationHasPrefix applies the HasPrefix predicate on the "shipping_information" field.
func ShippingInformationHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldShippingInformation, v))
}

// ShippingInformationHasSuffix applies the HasSuffix predicate on the "shipping_information" field.
func ShippingInformationHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldShippingInformation, v))
}

// ShippingInformationEqualFold applies the EqualFold predicate on the "shipping_information" field.
func ShippingInformationEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldShippingInformation, v))
}

// ShippingInformationContainsFold applies the ContainsFold predicate on the "shipping_information" field.
func ShippingInformationContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldShippingInformation, v))
}

// AvailabilityStatusEQ applies the EQ predicate on the "availability_status" field.
func AvailabilityStatusEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldAvailabilityStatus, v))
}

// AvailabilityStatusNEQ applies the NEQ predicate on the "availability_status" field.
func AvailabilityStatusNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldAvailabilityStatus, v))
}

// AvailabilityStatusIn applies the In predicate on the "availability_status" field.
func AvailabilityStatusIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldAvailabilityStatus, vs...))
}

// AvailabilityStatusNotIn applies the NotIn predicate on the "availability_status" field.
func AvailabilityStatusNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldAvailabilityStatus, vs...))
}

// AvailabilityStatusGT applies the GT predicate on the "availability_status" field.
func AvailabilityStatusGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldAvailabilityStatus, v))
}

// AvailabilityStatusGTE applies the GTE predicate on the "availability_status" field.
func AvailabilityStatusGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldAvailabilityStatus, v))
}

// AvailabilityStatusLT applies the LT predicate on the "availability_status" field.
func AvailabilityStatusLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldAvailabilityStatus, v))
}

// AvailabilityStatusLTE applies the LTE predicate on the "availability_status" field.
func AvailabilityStatusLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldAvailabilityStatus, v))
}

// AvailabilityStatusContains applies the Contains predicate on the "availability_status" field.
func AvailabilityStatusContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldAvailabilityStatus, v))
}

// AvailabilityStatusHasPrefix applies the HasPrefix predicate on the "availability_status" field.
func AvailabilityStatusHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldAvailabilityStatus, v))
}

// AvailabilityStatusHasSuffix applies the HasSuffix predicate on the "availability_status" field.
func AvailabilityStatusHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldAvailabilityStatus, v))
}

// AvailabilityStatusEqualFold applies the EqualFold predicate on the "availability_status" field.
func AvailabilityStatusEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldAvailabilityStatus, v))
}

// AvailabilityStatusContainsFold applies the ContainsFold predicate on the "availability_status" field.
func AvailabilityStatusContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldAvailabilityStatus, v))
}

// ReturnPolicyEQ applies the EQ predicate on the "return_policy" field.
func ReturnPolicyEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldReturnPolicy, v))
}

// ReturnPolicyNEQ applies the NEQ predicate on the "return_policy" field.
func ReturnPolicyNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldReturnPolicy, v))
}

// ReturnPolicyIn applies the In predicate on the "return_policy" field.
func ReturnPolicyIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldReturnPolicy, vs...))
}

// ReturnPolicyNotIn applies the NotIn predicate on the "return_policy" field.
func ReturnPolicyNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldReturnPolicy, vs...))
}

// ReturnPolicyGT applies the GT predicate on the "return_policy" field.
func ReturnPolicyGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldReturnPolicy, v))
}

// ReturnPolicyGTE applies the GTE predicate on the "return_policy" field.
func ReturnPolicyGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldReturnPolicy, v))
}

// ReturnPolicyLT applies the LT predicate on the "return_policy" field.
func ReturnPolicyLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldReturnPolicy, v))
}

// ReturnPolicyLTE applies the LTE predicate on the "return_policy" field.
func ReturnPolicyLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldReturnPolicy, v))
}

// ReturnPolicyContains applies the Contains predicate on the "return_policy" field.
func ReturnPolicyContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldReturnPolicy, v))
}

// ReturnPolicyHasPrefix applies the HasPrefix predicate on the "return_policy" field.
func ReturnPolicyHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldReturnPolicy, v))
}

// ReturnPolicyHasSuffix applies the HasSuffix predicate on the "return_policy" field.
func ReturnPolicyHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldReturnPolicy, v))
}

// ReturnPolicyEqualFold applies the EqualFold predicate on the "return_policy" field.
func ReturnPolicyEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldReturnPolicy, v))
}

// ReturnPolicyContainsFold applies the ContainsFold predicate on the "return_policy" field.
func ReturnPolicyContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldReturnPolicy, v))
}

// MinimumOrderQuantityEQ applies the EQ predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityEQ(v int) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldMinimumOrderQuantity, v))
}

// MinimumOrderQuantityNEQ applies the NEQ predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityNEQ(v int) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldMinimumOrderQuantity, v))
}

// MinimumOrderQuantityIn applies the In predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityIn(vs ...int) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldMinimumOrderQuantity, vs...))
}

// MinimumOrderQuantityNotIn applies the NotIn predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityNotIn(vs ...int) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldMinimumOrderQuantity, vs...))
}

// MinimumOrderQuantityGT applies the GT predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityGT(v int) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldMinimumOrderQuantity, v))
}

// MinimumOrderQuantityGTE applies the GTE predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityGTE(v int) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldMinimumOrderQuantity, v))
}

// MinimumOrderQuantityLT applies the LT predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityLT(v int) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldMinimumOrderQuantity, v))
}

// MinimumOrderQuantityLTE applies the LTE predicate on the "minimum_order_quantity" field.
func MinimumOrderQuantityLTE(v int) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldMinimumOrderQuantity, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldUpdatedAt, v))
}

// BarcodeEQ applies the EQ predicate on the "barcode" field.
func BarcodeEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldBarcode, v))
}

// BarcodeNEQ applies the NEQ predicate on the "barcode" field.
func BarcodeNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldBarcode, v))
}

// BarcodeIn applies the In predicate on the "barcode" field.
func BarcodeIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldBarcode, vs...))
}

// BarcodeNotIn applies the NotIn predicate on the "barcode" field.
func BarcodeNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldBarcode, vs...))
}

// BarcodeGT applies the GT predicate on the "barcode" field.
func BarcodeGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldBarcode, v))
}

// BarcodeGTE applies the GTE predicate on the "barcode" field.
func BarcodeGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldBarcode, v))
}

// BarcodeLT applies the LT predicate on the "barcode" field.
func BarcodeLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldBarcode, v))
}

// BarcodeLTE applies the LTE predicate on the "barcode" field.
func BarcodeLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldBarcode, v))
}

// BarcodeContains applies the Contains predicate on the "barcode" field.
func BarcodeContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldBarcode, v))
}

// BarcodeHasPrefix applies the HasPrefix predicate on the "barcode" field.
func BarcodeHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldBarcode, v))
}

// BarcodeHasSuffix applies the HasSuffix predicate on the "barcode" field.
func BarcodeHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldBarcode, v))
}

// BarcodeEqualFold applies the EqualFold predicate on the "barcode" field.
func BarcodeEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldBarcode, v))
}

// BarcodeContainsFold applies the ContainsFold predicate on the "barcode" field.
func BarcodeContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldBarcode, v))
}

// QrCodeEQ applies the EQ predicate on the "qr_code" field.
func QrCodeEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldQrCode, v))
}

// QrCodeNEQ applies the NEQ predicate on the "qr_code" field.
func QrCodeNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldQrCode, v))
}

// QrCodeIn applies the In predicate on the "qr_code" field.
func QrCodeIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldQrCode, vs...))
}

// QrCodeNotIn applies the NotIn predicate on the "qr_code" field.
func QrCodeNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldQrCode, vs...))
}

// QrCodeGT applies the GT predicate on the "qr_code" field.
func QrCodeGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldQrCode, v))
}

// QrCodeGTE applies the GTE predicate on the "qr_code" field.
func QrCodeGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldQrCode, v))
}

// QrCodeLT applies the LT predicate on the "qr_code" field.
func QrCodeLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldQrCode, v))
}

// QrCodeLTE applies the LTE predicate on the "qr_code" field.
func QrCodeLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldQrCode, v))
}

// QrCodeContains applies the Contains predicate on the "qr_code" field.
func QrCodeContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldQrCode, v))
}

// QrCodeHasPrefix applies the HasPrefix predicate on the "qr_code" field.
func QrCodeHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldQrCode, v))
}

// QrCodeHasSuffix applies the HasSuffix predicate on the "qr_code" field.
func QrCodeHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldQrCode, v))
}

// QrCodeEqualFold applies the EqualFold predicate on the "qr_code" field.
func QrCodeEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldQrCode, v))
}

// QrCodeContainsFold applies the ContainsFold predicate on the "qr_code" field.
func QrCodeContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldQrCode, v))
}

// ThumbnailEQ applies the EQ predicate on the "thumbnail" field.
func ThumbnailEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldEQ(FieldThumbnail, v))
}

// ThumbnailNEQ applies the NEQ predicate on the "thumbnail" field.
func ThumbnailNEQ(v string) predicate.Product {
	return predicate.Product(sql.FieldNEQ(FieldThumbnail, v))
}

// ThumbnailIn applies the In predicate on the "thumbnail" field.
func ThumbnailIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldIn(FieldThumbnail, vs...))
}

// ThumbnailNotIn applies the NotIn predicate on the "thumbnail" field.
func ThumbnailNotIn(vs ...string) predicate.Product {
	return predicate.Product(sql.FieldNotIn(FieldThumbnail, vs...))
}

// ThumbnailGT applies the GT predicate on the "thumbnail" field.
func ThumbnailGT(v string) predicate.Product {
	return predicate.Product(sql.FieldGT(FieldThumbnail, v))
}

// ThumbnailGTE applies the GTE predicate on the "thumbnail" field.
func ThumbnailGTE(v string) predicate.Product {
	return predicate.Product(sql.FieldGTE(FieldThumbnail, v))
}

// ThumbnailLT applies the LT predicate on the "thumbnail" field.
func ThumbnailLT(v string) predicate.Product {
	return predicate.Product(sql.FieldLT(FieldThumbnail, v))
}

// ThumbnailLTE applies the LTE predicate on the "thumbnail" field.
func ThumbnailLTE(v string) predicate.Product {
	return predicate.Product(sql.FieldLTE(FieldThumbnail, v))
}

// ThumbnailContains applies the Contains predicate on the "thumbnail" field.
func ThumbnailContains(v string) predicate.Product {
	return predicate.Product(sql.FieldContains(FieldThumbnail, v))
}

// ThumbnailHasPrefix applies the HasPrefix predicate on the "thumbnail" field.
func ThumbnailHasPrefix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasPrefix(FieldThumbnail, v))
}

// ThumbnailHasSuffix applies the HasSuffix predicate on the "thumbnail" field.
func ThumbnailHasSuffix(v string) predicate.Product {
	return predicate.Product(sql.FieldHasSuffix(FieldThumbnail, v))
}

// ThumbnailEqualFold applies the EqualFold predicate on the "thumbnail" field.
func ThumbnailEqualFold(v string) predicate.Product {
	return predicate.Product(sql.FieldEqualFold(FieldThumbnail, v))
}

// ThumbnailContainsFold applies the ContainsFold predicate on the "thumbnail" field.
func ThumbnailContainsFold(v string) predicate.Product {
	return predicate.Product(sql.FieldContainsFold(FieldThumbnail, v))
}

// HasOrderProducts applies the HasEdge predicate on the "order_products" edge.
func HasOrderProducts() predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrderProductsTable, OrderProductsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderProductsWith applies the HasEdge predicate on the "order_products" edge with a given conditions (other predicates).
func HasOrderProductsWith(preds ...predicate.OrderProducts) predicate.Product {
	return predicate.Product(func(s *sql.Selector) {
		step := newOrderProductsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Product) predicate.Product {
	return predicate.Product(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Product) predicate.Product {
	return predicate.Product(sql.NotPredicates(p))
}
