// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-server/ent/basket"
	"golang-server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BasketCreate is the builder for creating a Basket entity.
type BasketCreate struct {
	config
	mutation *BasketMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (bc *BasketCreate) SetUserID(i int) *BasketCreate {
	bc.mutation.SetUserID(i)
	return bc
}

// SetProductID sets the "product_id" field.
func (bc *BasketCreate) SetProductID(i int) *BasketCreate {
	bc.mutation.SetProductID(i)
	return bc
}

// SetQuantity sets the "quantity" field.
func (bc *BasketCreate) SetQuantity(i int) *BasketCreate {
	bc.mutation.SetQuantity(i)
	return bc
}

// SetPrice sets the "price" field.
func (bc *BasketCreate) SetPrice(f float64) *BasketCreate {
	bc.mutation.SetPrice(f)
	return bc
}

// SetAddedAt sets the "added_at" field.
func (bc *BasketCreate) SetAddedAt(t time.Time) *BasketCreate {
	bc.mutation.SetAddedAt(t)
	return bc
}

// SetNillableAddedAt sets the "added_at" field if the given value is not nil.
func (bc *BasketCreate) SetNillableAddedAt(t *time.Time) *BasketCreate {
	if t != nil {
		bc.SetAddedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BasketCreate) SetUpdatedAt(t time.Time) *BasketCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BasketCreate) SetNillableUpdatedAt(t *time.Time) *BasketCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BasketCreate) SetID(i int) *BasketCreate {
	bc.mutation.SetID(i)
	return bc
}

// SetUser sets the "user" edge to the User entity.
func (bc *BasketCreate) SetUser(u *User) *BasketCreate {
	return bc.SetUserID(u.ID)
}

// Mutation returns the BasketMutation object of the builder.
func (bc *BasketCreate) Mutation() *BasketMutation {
	return bc.mutation
}

// Save creates the Basket in the database.
func (bc *BasketCreate) Save(ctx context.Context) (*Basket, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BasketCreate) SaveX(ctx context.Context) *Basket {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BasketCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BasketCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BasketCreate) defaults() {
	if _, ok := bc.mutation.AddedAt(); !ok {
		v := basket.DefaultAddedAt()
		bc.mutation.SetAddedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := basket.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BasketCreate) check() error {
	if _, ok := bc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Basket.user_id"`)}
	}
	if v, ok := bc.mutation.UserID(); ok {
		if err := basket.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Basket.user_id": %w`, err)}
		}
	}
	if _, ok := bc.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "Basket.product_id"`)}
	}
	if v, ok := bc.mutation.ProductID(); ok {
		if err := basket.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "Basket.product_id": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Basket.quantity"`)}
	}
	if v, ok := bc.mutation.Quantity(); ok {
		if err := basket.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Basket.quantity": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Basket.price"`)}
	}
	if v, ok := bc.mutation.Price(); ok {
		if err := basket.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Basket.price": %w`, err)}
		}
	}
	if _, ok := bc.mutation.AddedAt(); !ok {
		return &ValidationError{Name: "added_at", err: errors.New(`ent: missing required field "Basket.added_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Basket.updated_at"`)}
	}
	if v, ok := bc.mutation.ID(); ok {
		if err := basket.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Basket.id": %w`, err)}
		}
	}
	if len(bc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Basket.user"`)}
	}
	return nil
}

func (bc *BasketCreate) sqlSave(ctx context.Context) (*Basket, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BasketCreate) createSpec() (*Basket, *sqlgraph.CreateSpec) {
	var (
		_node = &Basket{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(basket.Table, sqlgraph.NewFieldSpec(basket.FieldID, field.TypeInt))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.ProductID(); ok {
		_spec.SetField(basket.FieldProductID, field.TypeInt, value)
		_node.ProductID = value
	}
	if value, ok := bc.mutation.Quantity(); ok {
		_spec.SetField(basket.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := bc.mutation.Price(); ok {
		_spec.SetField(basket.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := bc.mutation.AddedAt(); ok {
		_spec.SetField(basket.FieldAddedAt, field.TypeTime, value)
		_node.AddedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(basket.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := bc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   basket.UserTable,
			Columns: []string{basket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BasketCreateBulk is the builder for creating many Basket entities in bulk.
type BasketCreateBulk struct {
	config
	err      error
	builders []*BasketCreate
}

// Save creates the Basket entities in the database.
func (bcb *BasketCreateBulk) Save(ctx context.Context) ([]*Basket, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Basket, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BasketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BasketCreateBulk) SaveX(ctx context.Context) []*Basket {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BasketCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BasketCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
