// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-server/ent/basket"
	"golang-server/ent/predicate"
	"golang-server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BasketUpdate is the builder for updating Basket entities.
type BasketUpdate struct {
	config
	hooks    []Hook
	mutation *BasketMutation
}

// Where appends a list predicates to the BasketUpdate builder.
func (bu *BasketUpdate) Where(ps ...predicate.Basket) *BasketUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetUserID sets the "user_id" field.
func (bu *BasketUpdate) SetUserID(i int) *BasketUpdate {
	bu.mutation.SetUserID(i)
	return bu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (bu *BasketUpdate) SetNillableUserID(i *int) *BasketUpdate {
	if i != nil {
		bu.SetUserID(*i)
	}
	return bu
}

// SetProductID sets the "product_id" field.
func (bu *BasketUpdate) SetProductID(i int) *BasketUpdate {
	bu.mutation.ResetProductID()
	bu.mutation.SetProductID(i)
	return bu
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (bu *BasketUpdate) SetNillableProductID(i *int) *BasketUpdate {
	if i != nil {
		bu.SetProductID(*i)
	}
	return bu
}

// AddProductID adds i to the "product_id" field.
func (bu *BasketUpdate) AddProductID(i int) *BasketUpdate {
	bu.mutation.AddProductID(i)
	return bu
}

// SetQuantity sets the "quantity" field.
func (bu *BasketUpdate) SetQuantity(i int) *BasketUpdate {
	bu.mutation.ResetQuantity()
	bu.mutation.SetQuantity(i)
	return bu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (bu *BasketUpdate) SetNillableQuantity(i *int) *BasketUpdate {
	if i != nil {
		bu.SetQuantity(*i)
	}
	return bu
}

// AddQuantity adds i to the "quantity" field.
func (bu *BasketUpdate) AddQuantity(i int) *BasketUpdate {
	bu.mutation.AddQuantity(i)
	return bu
}

// SetPrice sets the "price" field.
func (bu *BasketUpdate) SetPrice(f float64) *BasketUpdate {
	bu.mutation.ResetPrice()
	bu.mutation.SetPrice(f)
	return bu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (bu *BasketUpdate) SetNillablePrice(f *float64) *BasketUpdate {
	if f != nil {
		bu.SetPrice(*f)
	}
	return bu
}

// AddPrice adds f to the "price" field.
func (bu *BasketUpdate) AddPrice(f float64) *BasketUpdate {
	bu.mutation.AddPrice(f)
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BasketUpdate) SetUpdatedAt(t time.Time) *BasketUpdate {
	bu.mutation.SetUpdatedAt(t)
	return bu
}

// SetUser sets the "user" edge to the User entity.
func (bu *BasketUpdate) SetUser(u *User) *BasketUpdate {
	return bu.SetUserID(u.ID)
}

// Mutation returns the BasketMutation object of the builder.
func (bu *BasketUpdate) Mutation() *BasketMutation {
	return bu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (bu *BasketUpdate) ClearUser() *BasketUpdate {
	bu.mutation.ClearUser()
	return bu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BasketUpdate) Save(ctx context.Context) (int, error) {
	bu.defaults()
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BasketUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BasketUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BasketUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bu *BasketUpdate) defaults() {
	if _, ok := bu.mutation.UpdatedAt(); !ok {
		v := basket.UpdateDefaultUpdatedAt()
		bu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BasketUpdate) check() error {
	if v, ok := bu.mutation.UserID(); ok {
		if err := basket.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Basket.user_id": %w`, err)}
		}
	}
	if v, ok := bu.mutation.ProductID(); ok {
		if err := basket.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "Basket.product_id": %w`, err)}
		}
	}
	if v, ok := bu.mutation.Quantity(); ok {
		if err := basket.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Basket.quantity": %w`, err)}
		}
	}
	if v, ok := bu.mutation.Price(); ok {
		if err := basket.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Basket.price": %w`, err)}
		}
	}
	if bu.mutation.UserCleared() && len(bu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Basket.user"`)
	}
	return nil
}

func (bu *BasketUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(basket.Table, basket.Columns, sqlgraph.NewFieldSpec(basket.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.ProductID(); ok {
		_spec.SetField(basket.FieldProductID, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedProductID(); ok {
		_spec.AddField(basket.FieldProductID, field.TypeInt, value)
	}
	if value, ok := bu.mutation.Quantity(); ok {
		_spec.SetField(basket.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedQuantity(); ok {
		_spec.AddField(basket.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := bu.mutation.Price(); ok {
		_spec.SetField(basket.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.AddedPrice(); ok {
		_spec.AddField(basket.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(basket.FieldUpdatedAt, field.TypeTime, value)
	}
	if bu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   basket.UserTable,
			Columns: []string{basket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   basket.UserTable,
			Columns: []string{basket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{basket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BasketUpdateOne is the builder for updating a single Basket entity.
type BasketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BasketMutation
}

// SetUserID sets the "user_id" field.
func (buo *BasketUpdateOne) SetUserID(i int) *BasketUpdateOne {
	buo.mutation.SetUserID(i)
	return buo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (buo *BasketUpdateOne) SetNillableUserID(i *int) *BasketUpdateOne {
	if i != nil {
		buo.SetUserID(*i)
	}
	return buo
}

// SetProductID sets the "product_id" field.
func (buo *BasketUpdateOne) SetProductID(i int) *BasketUpdateOne {
	buo.mutation.ResetProductID()
	buo.mutation.SetProductID(i)
	return buo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (buo *BasketUpdateOne) SetNillableProductID(i *int) *BasketUpdateOne {
	if i != nil {
		buo.SetProductID(*i)
	}
	return buo
}

// AddProductID adds i to the "product_id" field.
func (buo *BasketUpdateOne) AddProductID(i int) *BasketUpdateOne {
	buo.mutation.AddProductID(i)
	return buo
}

// SetQuantity sets the "quantity" field.
func (buo *BasketUpdateOne) SetQuantity(i int) *BasketUpdateOne {
	buo.mutation.ResetQuantity()
	buo.mutation.SetQuantity(i)
	return buo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (buo *BasketUpdateOne) SetNillableQuantity(i *int) *BasketUpdateOne {
	if i != nil {
		buo.SetQuantity(*i)
	}
	return buo
}

// AddQuantity adds i to the "quantity" field.
func (buo *BasketUpdateOne) AddQuantity(i int) *BasketUpdateOne {
	buo.mutation.AddQuantity(i)
	return buo
}

// SetPrice sets the "price" field.
func (buo *BasketUpdateOne) SetPrice(f float64) *BasketUpdateOne {
	buo.mutation.ResetPrice()
	buo.mutation.SetPrice(f)
	return buo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (buo *BasketUpdateOne) SetNillablePrice(f *float64) *BasketUpdateOne {
	if f != nil {
		buo.SetPrice(*f)
	}
	return buo
}

// AddPrice adds f to the "price" field.
func (buo *BasketUpdateOne) AddPrice(f float64) *BasketUpdateOne {
	buo.mutation.AddPrice(f)
	return buo
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BasketUpdateOne) SetUpdatedAt(t time.Time) *BasketUpdateOne {
	buo.mutation.SetUpdatedAt(t)
	return buo
}

// SetUser sets the "user" edge to the User entity.
func (buo *BasketUpdateOne) SetUser(u *User) *BasketUpdateOne {
	return buo.SetUserID(u.ID)
}

// Mutation returns the BasketMutation object of the builder.
func (buo *BasketUpdateOne) Mutation() *BasketMutation {
	return buo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (buo *BasketUpdateOne) ClearUser() *BasketUpdateOne {
	buo.mutation.ClearUser()
	return buo
}

// Where appends a list predicates to the BasketUpdate builder.
func (buo *BasketUpdateOne) Where(ps ...predicate.Basket) *BasketUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BasketUpdateOne) Select(field string, fields ...string) *BasketUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Basket entity.
func (buo *BasketUpdateOne) Save(ctx context.Context) (*Basket, error) {
	buo.defaults()
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BasketUpdateOne) SaveX(ctx context.Context) *Basket {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BasketUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BasketUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (buo *BasketUpdateOne) defaults() {
	if _, ok := buo.mutation.UpdatedAt(); !ok {
		v := basket.UpdateDefaultUpdatedAt()
		buo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BasketUpdateOne) check() error {
	if v, ok := buo.mutation.UserID(); ok {
		if err := basket.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Basket.user_id": %w`, err)}
		}
	}
	if v, ok := buo.mutation.ProductID(); ok {
		if err := basket.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "Basket.product_id": %w`, err)}
		}
	}
	if v, ok := buo.mutation.Quantity(); ok {
		if err := basket.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "Basket.quantity": %w`, err)}
		}
	}
	if v, ok := buo.mutation.Price(); ok {
		if err := basket.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Basket.price": %w`, err)}
		}
	}
	if buo.mutation.UserCleared() && len(buo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Basket.user"`)
	}
	return nil
}

func (buo *BasketUpdateOne) sqlSave(ctx context.Context) (_node *Basket, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(basket.Table, basket.Columns, sqlgraph.NewFieldSpec(basket.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Basket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, basket.FieldID)
		for _, f := range fields {
			if !basket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != basket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.ProductID(); ok {
		_spec.SetField(basket.FieldProductID, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedProductID(); ok {
		_spec.AddField(basket.FieldProductID, field.TypeInt, value)
	}
	if value, ok := buo.mutation.Quantity(); ok {
		_spec.SetField(basket.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedQuantity(); ok {
		_spec.AddField(basket.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := buo.mutation.Price(); ok {
		_spec.SetField(basket.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.AddedPrice(); ok {
		_spec.AddField(basket.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(basket.FieldUpdatedAt, field.TypeTime, value)
	}
	if buo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   basket.UserTable,
			Columns: []string{basket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   basket.UserTable,
			Columns: []string{basket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Basket{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{basket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
