// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"golang-server/ent/order"
	"golang-server/ent/orderproducts"
	"golang-server/ent/product"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OrderProducts is the model entity for the OrderProducts schema.
type OrderProducts struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderProductsQuery when eager-loading is set.
	Edges                  OrderProductsEdges `json:"edges"`
	order_order_products   *int
	product_order_products *int
	selectValues           sql.SelectValues
}

// OrderProductsEdges holds the relations/edges for other nodes in the graph.
type OrderProductsEdges struct {
	// Order holds the value of the order edge.
	Order *Order `json:"order,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderProductsEdges) OrderOrErr() (*Order, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderProductsEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderProducts) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orderproducts.FieldID, orderproducts.FieldQuantity:
			values[i] = new(sql.NullInt64)
		case orderproducts.FieldCreatedAt, orderproducts.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case orderproducts.ForeignKeys[0]: // order_order_products
			values[i] = new(sql.NullInt64)
		case orderproducts.ForeignKeys[1]: // product_order_products
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderProducts fields.
func (op *OrderProducts) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orderproducts.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			op.ID = int(value.Int64)
		case orderproducts.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				op.Quantity = int(value.Int64)
			}
		case orderproducts.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				op.CreatedAt = value.Time
			}
		case orderproducts.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				op.UpdatedAt = value.Time
			}
		case orderproducts.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field order_order_products", value)
			} else if value.Valid {
				op.order_order_products = new(int)
				*op.order_order_products = int(value.Int64)
			}
		case orderproducts.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field product_order_products", value)
			} else if value.Valid {
				op.product_order_products = new(int)
				*op.product_order_products = int(value.Int64)
			}
		default:
			op.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderProducts.
// This includes values selected through modifiers, order, etc.
func (op *OrderProducts) Value(name string) (ent.Value, error) {
	return op.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the OrderProducts entity.
func (op *OrderProducts) QueryOrder() *OrderQuery {
	return NewOrderProductsClient(op.config).QueryOrder(op)
}

// QueryProduct queries the "product" edge of the OrderProducts entity.
func (op *OrderProducts) QueryProduct() *ProductQuery {
	return NewOrderProductsClient(op.config).QueryProduct(op)
}

// Update returns a builder for updating this OrderProducts.
// Note that you need to call OrderProducts.Unwrap() before calling this method if this OrderProducts
// was returned from a transaction, and the transaction was committed or rolled back.
func (op *OrderProducts) Update() *OrderProductsUpdateOne {
	return NewOrderProductsClient(op.config).UpdateOne(op)
}

// Unwrap unwraps the OrderProducts entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (op *OrderProducts) Unwrap() *OrderProducts {
	_tx, ok := op.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderProducts is not a transactional entity")
	}
	op.config.driver = _tx.drv
	return op
}

// String implements the fmt.Stringer.
func (op *OrderProducts) String() string {
	var builder strings.Builder
	builder.WriteString("OrderProducts(")
	builder.WriteString(fmt.Sprintf("id=%v, ", op.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", op.Quantity))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(op.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(op.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrderProductsSlice is a parsable slice of OrderProducts.
type OrderProductsSlice []*OrderProducts
