// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"golang-server/ent/orderproducts"
	"golang-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderProductsDelete is the builder for deleting a OrderProducts entity.
type OrderProductsDelete struct {
	config
	hooks    []Hook
	mutation *OrderProductsMutation
}

// Where appends a list predicates to the OrderProductsDelete builder.
func (opd *OrderProductsDelete) Where(ps ...predicate.OrderProducts) *OrderProductsDelete {
	opd.mutation.Where(ps...)
	return opd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (opd *OrderProductsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, opd.sqlExec, opd.mutation, opd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (opd *OrderProductsDelete) ExecX(ctx context.Context) int {
	n, err := opd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (opd *OrderProductsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderproducts.Table, sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt))
	if ps := opd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, opd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	opd.mutation.done = true
	return affected, err
}

// OrderProductsDeleteOne is the builder for deleting a single OrderProducts entity.
type OrderProductsDeleteOne struct {
	opd *OrderProductsDelete
}

// Where appends a list predicates to the OrderProductsDelete builder.
func (opdo *OrderProductsDeleteOne) Where(ps ...predicate.OrderProducts) *OrderProductsDeleteOne {
	opdo.opd.mutation.Where(ps...)
	return opdo
}

// Exec executes the deletion query.
func (opdo *OrderProductsDeleteOne) Exec(ctx context.Context) error {
	n, err := opdo.opd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderproducts.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (opdo *OrderProductsDeleteOne) ExecX(ctx context.Context) {
	if err := opdo.Exec(ctx); err != nil {
		panic(err)
	}
}
