// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-server/ent/order"
	"golang-server/ent/orderproducts"
	"golang-server/ent/product"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderProductsCreate is the builder for creating a OrderProducts entity.
type OrderProductsCreate struct {
	config
	mutation *OrderProductsMutation
	hooks    []Hook
}

// SetQuantity sets the "quantity" field.
func (opc *OrderProductsCreate) SetQuantity(i int) *OrderProductsCreate {
	opc.mutation.SetQuantity(i)
	return opc
}

// SetCreatedAt sets the "created_at" field.
func (opc *OrderProductsCreate) SetCreatedAt(t time.Time) *OrderProductsCreate {
	opc.mutation.SetCreatedAt(t)
	return opc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (opc *OrderProductsCreate) SetNillableCreatedAt(t *time.Time) *OrderProductsCreate {
	if t != nil {
		opc.SetCreatedAt(*t)
	}
	return opc
}

// SetUpdatedAt sets the "updated_at" field.
func (opc *OrderProductsCreate) SetUpdatedAt(t time.Time) *OrderProductsCreate {
	opc.mutation.SetUpdatedAt(t)
	return opc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (opc *OrderProductsCreate) SetNillableUpdatedAt(t *time.Time) *OrderProductsCreate {
	if t != nil {
		opc.SetUpdatedAt(*t)
	}
	return opc
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (opc *OrderProductsCreate) SetOrderID(id int) *OrderProductsCreate {
	opc.mutation.SetOrderID(id)
	return opc
}

// SetOrder sets the "order" edge to the Order entity.
func (opc *OrderProductsCreate) SetOrder(o *Order) *OrderProductsCreate {
	return opc.SetOrderID(o.ID)
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (opc *OrderProductsCreate) SetProductID(id int) *OrderProductsCreate {
	opc.mutation.SetProductID(id)
	return opc
}

// SetProduct sets the "product" edge to the Product entity.
func (opc *OrderProductsCreate) SetProduct(p *Product) *OrderProductsCreate {
	return opc.SetProductID(p.ID)
}

// Mutation returns the OrderProductsMutation object of the builder.
func (opc *OrderProductsCreate) Mutation() *OrderProductsMutation {
	return opc.mutation
}

// Save creates the OrderProducts in the database.
func (opc *OrderProductsCreate) Save(ctx context.Context) (*OrderProducts, error) {
	opc.defaults()
	return withHooks(ctx, opc.sqlSave, opc.mutation, opc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (opc *OrderProductsCreate) SaveX(ctx context.Context) *OrderProducts {
	v, err := opc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (opc *OrderProductsCreate) Exec(ctx context.Context) error {
	_, err := opc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opc *OrderProductsCreate) ExecX(ctx context.Context) {
	if err := opc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (opc *OrderProductsCreate) defaults() {
	if _, ok := opc.mutation.CreatedAt(); !ok {
		v := orderproducts.DefaultCreatedAt()
		opc.mutation.SetCreatedAt(v)
	}
	if _, ok := opc.mutation.UpdatedAt(); !ok {
		v := orderproducts.DefaultUpdatedAt()
		opc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (opc *OrderProductsCreate) check() error {
	if _, ok := opc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "OrderProducts.quantity"`)}
	}
	if v, ok := opc.mutation.Quantity(); ok {
		if err := orderproducts.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderProducts.quantity": %w`, err)}
		}
	}
	if _, ok := opc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrderProducts.created_at"`)}
	}
	if _, ok := opc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrderProducts.updated_at"`)}
	}
	if len(opc.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "OrderProducts.order"`)}
	}
	if len(opc.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "OrderProducts.product"`)}
	}
	return nil
}

func (opc *OrderProductsCreate) sqlSave(ctx context.Context) (*OrderProducts, error) {
	if err := opc.check(); err != nil {
		return nil, err
	}
	_node, _spec := opc.createSpec()
	if err := sqlgraph.CreateNode(ctx, opc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	opc.mutation.id = &_node.ID
	opc.mutation.done = true
	return _node, nil
}

func (opc *OrderProductsCreate) createSpec() (*OrderProducts, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderProducts{config: opc.config}
		_spec = sqlgraph.NewCreateSpec(orderproducts.Table, sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt))
	)
	if value, ok := opc.mutation.Quantity(); ok {
		_spec.SetField(orderproducts.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := opc.mutation.CreatedAt(); ok {
		_spec.SetField(orderproducts.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := opc.mutation.UpdatedAt(); ok {
		_spec.SetField(orderproducts.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := opc.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproducts.OrderTable,
			Columns: []string{orderproducts.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_order_products = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := opc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproducts.ProductTable,
			Columns: []string{orderproducts.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.product_order_products = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderProductsCreateBulk is the builder for creating many OrderProducts entities in bulk.
type OrderProductsCreateBulk struct {
	config
	err      error
	builders []*OrderProductsCreate
}

// Save creates the OrderProducts entities in the database.
func (opcb *OrderProductsCreateBulk) Save(ctx context.Context) ([]*OrderProducts, error) {
	if opcb.err != nil {
		return nil, opcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(opcb.builders))
	nodes := make([]*OrderProducts, len(opcb.builders))
	mutators := make([]Mutator, len(opcb.builders))
	for i := range opcb.builders {
		func(i int, root context.Context) {
			builder := opcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderProductsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, opcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, opcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, opcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (opcb *OrderProductsCreateBulk) SaveX(ctx context.Context) []*OrderProducts {
	v, err := opcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (opcb *OrderProductsCreateBulk) Exec(ctx context.Context) error {
	_, err := opcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opcb *OrderProductsCreateBulk) ExecX(ctx context.Context) {
	if err := opcb.Exec(ctx); err != nil {
		panic(err)
	}
}
