// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-server/ent/order"
	"golang-server/ent/orderproducts"
	"golang-server/ent/predicate"
	"golang-server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetPaymentType sets the "paymentType" field.
func (ou *OrderUpdate) SetPaymentType(ot order.PaymentType) *OrderUpdate {
	ou.mutation.SetPaymentType(ot)
	return ou
}

// SetNillablePaymentType sets the "paymentType" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePaymentType(ot *order.PaymentType) *OrderUpdate {
	if ot != nil {
		ou.SetPaymentType(*ot)
	}
	return ou
}

// SetAddress sets the "address" field.
func (ou *OrderUpdate) SetAddress(s string) *OrderUpdate {
	ou.mutation.SetAddress(s)
	return ou
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableAddress(s *string) *OrderUpdate {
	if s != nil {
		ou.SetAddress(*s)
	}
	return ou
}

// SetCity sets the "city" field.
func (ou *OrderUpdate) SetCity(s string) *OrderUpdate {
	ou.mutation.SetCity(s)
	return ou
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCity(s *string) *OrderUpdate {
	if s != nil {
		ou.SetCity(*s)
	}
	return ou
}

// SetState sets the "state" field.
func (ou *OrderUpdate) SetState(s string) *OrderUpdate {
	ou.mutation.SetState(s)
	return ou
}

// SetNillableState sets the "state" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableState(s *string) *OrderUpdate {
	if s != nil {
		ou.SetState(*s)
	}
	return ou
}

// SetZip sets the "zip" field.
func (ou *OrderUpdate) SetZip(s string) *OrderUpdate {
	ou.mutation.SetZip(s)
	return ou
}

// SetNillableZip sets the "zip" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableZip(s *string) *OrderUpdate {
	if s != nil {
		ou.SetZip(*s)
	}
	return ou
}

// SetUserID sets the "user_id" field.
func (ou *OrderUpdate) SetUserID(i int) *OrderUpdate {
	ou.mutation.SetUserID(i)
	return ou
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableUserID(i *int) *OrderUpdate {
	if i != nil {
		ou.SetUserID(*i)
	}
	return ou
}

// SetTotalPrice sets the "total_price" field.
func (ou *OrderUpdate) SetTotalPrice(f float64) *OrderUpdate {
	ou.mutation.ResetTotalPrice()
	ou.mutation.SetTotalPrice(f)
	return ou
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableTotalPrice(f *float64) *OrderUpdate {
	if f != nil {
		ou.SetTotalPrice(*f)
	}
	return ou
}

// AddTotalPrice adds f to the "total_price" field.
func (ou *OrderUpdate) AddTotalPrice(f float64) *OrderUpdate {
	ou.mutation.AddTotalPrice(f)
	return ou
}

// SetStatus sets the "status" field.
func (ou *OrderUpdate) SetStatus(o order.Status) *OrderUpdate {
	ou.mutation.SetStatus(o)
	return ou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableStatus(o *order.Status) *OrderUpdate {
	if o != nil {
		ou.SetStatus(*o)
	}
	return ou
}

// SetCreatedAt sets the "created_at" field.
func (ou *OrderUpdate) SetCreatedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetCreatedAt(t)
	return ou
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCreatedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetCreatedAt(*t)
	}
	return ou
}

// SetUpdatedAt sets the "updated_at" field.
func (ou *OrderUpdate) SetUpdatedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// AddOrderProductIDs adds the "order_products" edge to the OrderProducts entity by IDs.
func (ou *OrderUpdate) AddOrderProductIDs(ids ...int) *OrderUpdate {
	ou.mutation.AddOrderProductIDs(ids...)
	return ou
}

// AddOrderProducts adds the "order_products" edges to the OrderProducts entity.
func (ou *OrderUpdate) AddOrderProducts(o ...*OrderProducts) *OrderUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.AddOrderProductIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (ou *OrderUpdate) SetUser(u *User) *OrderUpdate {
	return ou.SetUserID(u.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// ClearOrderProducts clears all "order_products" edges to the OrderProducts entity.
func (ou *OrderUpdate) ClearOrderProducts() *OrderUpdate {
	ou.mutation.ClearOrderProducts()
	return ou
}

// RemoveOrderProductIDs removes the "order_products" edge to OrderProducts entities by IDs.
func (ou *OrderUpdate) RemoveOrderProductIDs(ids ...int) *OrderUpdate {
	ou.mutation.RemoveOrderProductIDs(ids...)
	return ou
}

// RemoveOrderProducts removes "order_products" edges to OrderProducts entities.
func (ou *OrderUpdate) RemoveOrderProducts(o ...*OrderProducts) *OrderUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.RemoveOrderProductIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (ou *OrderUpdate) ClearUser() *OrderUpdate {
	ou.mutation.ClearUser()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrderUpdate) defaults() {
	if _, ok := ou.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		ou.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.PaymentType(); ok {
		if err := order.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "paymentType", err: fmt.Errorf(`ent: validator failed for field "Order.paymentType": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Address(); ok {
		if err := order.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Order.address": %w`, err)}
		}
	}
	if v, ok := ou.mutation.City(); ok {
		if err := order.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Order.city": %w`, err)}
		}
	}
	if v, ok := ou.mutation.State(); ok {
		if err := order.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Order.state": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Zip(); ok {
		if err := order.ZipValidator(v); err != nil {
			return &ValidationError{Name: "zip", err: fmt.Errorf(`ent: validator failed for field "Order.zip": %w`, err)}
		}
	}
	if v, ok := ou.mutation.TotalPrice(); ok {
		if err := order.TotalPriceValidator(v); err != nil {
			return &ValidationError{Name: "total_price", err: fmt.Errorf(`ent: validator failed for field "Order.total_price": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if ou.mutation.UserCleared() && len(ou.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.PaymentType(); ok {
		_spec.SetField(order.FieldPaymentType, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.Address(); ok {
		_spec.SetField(order.FieldAddress, field.TypeString, value)
	}
	if value, ok := ou.mutation.City(); ok {
		_spec.SetField(order.FieldCity, field.TypeString, value)
	}
	if value, ok := ou.mutation.State(); ok {
		_spec.SetField(order.FieldState, field.TypeString, value)
	}
	if value, ok := ou.mutation.Zip(); ok {
		_spec.SetField(order.FieldZip, field.TypeString, value)
	}
	if value, ok := ou.mutation.TotalPrice(); ok {
		_spec.SetField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.AddedTotalPrice(); ok {
		_spec.AddField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := ou.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if ou.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderProductsTable,
			Columns: []string{order.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.RemovedOrderProductsIDs(); len(nodes) > 0 && !ou.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderProductsTable,
			Columns: []string{order.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.OrderProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderProductsTable,
			Columns: []string{order.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ou.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetPaymentType sets the "paymentType" field.
func (ouo *OrderUpdateOne) SetPaymentType(ot order.PaymentType) *OrderUpdateOne {
	ouo.mutation.SetPaymentType(ot)
	return ouo
}

// SetNillablePaymentType sets the "paymentType" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePaymentType(ot *order.PaymentType) *OrderUpdateOne {
	if ot != nil {
		ouo.SetPaymentType(*ot)
	}
	return ouo
}

// SetAddress sets the "address" field.
func (ouo *OrderUpdateOne) SetAddress(s string) *OrderUpdateOne {
	ouo.mutation.SetAddress(s)
	return ouo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableAddress(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetAddress(*s)
	}
	return ouo
}

// SetCity sets the "city" field.
func (ouo *OrderUpdateOne) SetCity(s string) *OrderUpdateOne {
	ouo.mutation.SetCity(s)
	return ouo
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCity(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetCity(*s)
	}
	return ouo
}

// SetState sets the "state" field.
func (ouo *OrderUpdateOne) SetState(s string) *OrderUpdateOne {
	ouo.mutation.SetState(s)
	return ouo
}

// SetNillableState sets the "state" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableState(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetState(*s)
	}
	return ouo
}

// SetZip sets the "zip" field.
func (ouo *OrderUpdateOne) SetZip(s string) *OrderUpdateOne {
	ouo.mutation.SetZip(s)
	return ouo
}

// SetNillableZip sets the "zip" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableZip(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetZip(*s)
	}
	return ouo
}

// SetUserID sets the "user_id" field.
func (ouo *OrderUpdateOne) SetUserID(i int) *OrderUpdateOne {
	ouo.mutation.SetUserID(i)
	return ouo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableUserID(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetUserID(*i)
	}
	return ouo
}

// SetTotalPrice sets the "total_price" field.
func (ouo *OrderUpdateOne) SetTotalPrice(f float64) *OrderUpdateOne {
	ouo.mutation.ResetTotalPrice()
	ouo.mutation.SetTotalPrice(f)
	return ouo
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableTotalPrice(f *float64) *OrderUpdateOne {
	if f != nil {
		ouo.SetTotalPrice(*f)
	}
	return ouo
}

// AddTotalPrice adds f to the "total_price" field.
func (ouo *OrderUpdateOne) AddTotalPrice(f float64) *OrderUpdateOne {
	ouo.mutation.AddTotalPrice(f)
	return ouo
}

// SetStatus sets the "status" field.
func (ouo *OrderUpdateOne) SetStatus(o order.Status) *OrderUpdateOne {
	ouo.mutation.SetStatus(o)
	return ouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableStatus(o *order.Status) *OrderUpdateOne {
	if o != nil {
		ouo.SetStatus(*o)
	}
	return ouo
}

// SetCreatedAt sets the "created_at" field.
func (ouo *OrderUpdateOne) SetCreatedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetCreatedAt(t)
	return ouo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCreatedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetCreatedAt(*t)
	}
	return ouo
}

// SetUpdatedAt sets the "updated_at" field.
func (ouo *OrderUpdateOne) SetUpdatedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// AddOrderProductIDs adds the "order_products" edge to the OrderProducts entity by IDs.
func (ouo *OrderUpdateOne) AddOrderProductIDs(ids ...int) *OrderUpdateOne {
	ouo.mutation.AddOrderProductIDs(ids...)
	return ouo
}

// AddOrderProducts adds the "order_products" edges to the OrderProducts entity.
func (ouo *OrderUpdateOne) AddOrderProducts(o ...*OrderProducts) *OrderUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.AddOrderProductIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (ouo *OrderUpdateOne) SetUser(u *User) *OrderUpdateOne {
	return ouo.SetUserID(u.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// ClearOrderProducts clears all "order_products" edges to the OrderProducts entity.
func (ouo *OrderUpdateOne) ClearOrderProducts() *OrderUpdateOne {
	ouo.mutation.ClearOrderProducts()
	return ouo
}

// RemoveOrderProductIDs removes the "order_products" edge to OrderProducts entities by IDs.
func (ouo *OrderUpdateOne) RemoveOrderProductIDs(ids ...int) *OrderUpdateOne {
	ouo.mutation.RemoveOrderProductIDs(ids...)
	return ouo
}

// RemoveOrderProducts removes "order_products" edges to OrderProducts entities.
func (ouo *OrderUpdateOne) RemoveOrderProducts(o ...*OrderProducts) *OrderUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.RemoveOrderProductIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (ouo *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	ouo.mutation.ClearUser()
	return ouo
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrderUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		ouo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.PaymentType(); ok {
		if err := order.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "paymentType", err: fmt.Errorf(`ent: validator failed for field "Order.paymentType": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Address(); ok {
		if err := order.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Order.address": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.City(); ok {
		if err := order.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Order.city": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.State(); ok {
		if err := order.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Order.state": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Zip(); ok {
		if err := order.ZipValidator(v); err != nil {
			return &ValidationError{Name: "zip", err: fmt.Errorf(`ent: validator failed for field "Order.zip": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.TotalPrice(); ok {
		if err := order.TotalPriceValidator(v); err != nil {
			return &ValidationError{Name: "total_price", err: fmt.Errorf(`ent: validator failed for field "Order.total_price": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if ouo.mutation.UserCleared() && len(ouo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.PaymentType(); ok {
		_spec.SetField(order.FieldPaymentType, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.Address(); ok {
		_spec.SetField(order.FieldAddress, field.TypeString, value)
	}
	if value, ok := ouo.mutation.City(); ok {
		_spec.SetField(order.FieldCity, field.TypeString, value)
	}
	if value, ok := ouo.mutation.State(); ok {
		_spec.SetField(order.FieldState, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Zip(); ok {
		_spec.SetField(order.FieldZip, field.TypeString, value)
	}
	if value, ok := ouo.mutation.TotalPrice(); ok {
		_spec.SetField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.AddedTotalPrice(); ok {
		_spec.AddField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := ouo.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if ouo.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderProductsTable,
			Columns: []string{order.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.RemovedOrderProductsIDs(); len(nodes) > 0 && !ouo.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderProductsTable,
			Columns: []string{order.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.OrderProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.OrderProductsTable,
			Columns: []string{order.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
