// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-server/ent/order"
	"golang-server/ent/orderproducts"
	"golang-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderProductsUpdate is the builder for updating OrderProducts entities.
type OrderProductsUpdate struct {
	config
	hooks    []Hook
	mutation *OrderProductsMutation
}

// Where appends a list predicates to the OrderProductsUpdate builder.
func (opu *OrderProductsUpdate) Where(ps ...predicate.OrderProducts) *OrderProductsUpdate {
	opu.mutation.Where(ps...)
	return opu
}

// SetQuantity sets the "quantity" field.
func (opu *OrderProductsUpdate) SetQuantity(i int) *OrderProductsUpdate {
	opu.mutation.ResetQuantity()
	opu.mutation.SetQuantity(i)
	return opu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (opu *OrderProductsUpdate) SetNillableQuantity(i *int) *OrderProductsUpdate {
	if i != nil {
		opu.SetQuantity(*i)
	}
	return opu
}

// AddQuantity adds i to the "quantity" field.
func (opu *OrderProductsUpdate) AddQuantity(i int) *OrderProductsUpdate {
	opu.mutation.AddQuantity(i)
	return opu
}

// SetCreatedAt sets the "created_at" field.
func (opu *OrderProductsUpdate) SetCreatedAt(t time.Time) *OrderProductsUpdate {
	opu.mutation.SetCreatedAt(t)
	return opu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (opu *OrderProductsUpdate) SetNillableCreatedAt(t *time.Time) *OrderProductsUpdate {
	if t != nil {
		opu.SetCreatedAt(*t)
	}
	return opu
}

// SetUpdatedAt sets the "updated_at" field.
func (opu *OrderProductsUpdate) SetUpdatedAt(t time.Time) *OrderProductsUpdate {
	opu.mutation.SetUpdatedAt(t)
	return opu
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (opu *OrderProductsUpdate) SetOrderID(id int) *OrderProductsUpdate {
	opu.mutation.SetOrderID(id)
	return opu
}

// SetOrder sets the "order" edge to the Order entity.
func (opu *OrderProductsUpdate) SetOrder(o *Order) *OrderProductsUpdate {
	return opu.SetOrderID(o.ID)
}

// Mutation returns the OrderProductsMutation object of the builder.
func (opu *OrderProductsUpdate) Mutation() *OrderProductsMutation {
	return opu.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (opu *OrderProductsUpdate) ClearOrder() *OrderProductsUpdate {
	opu.mutation.ClearOrder()
	return opu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (opu *OrderProductsUpdate) Save(ctx context.Context) (int, error) {
	opu.defaults()
	return withHooks(ctx, opu.sqlSave, opu.mutation, opu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (opu *OrderProductsUpdate) SaveX(ctx context.Context) int {
	affected, err := opu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (opu *OrderProductsUpdate) Exec(ctx context.Context) error {
	_, err := opu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opu *OrderProductsUpdate) ExecX(ctx context.Context) {
	if err := opu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (opu *OrderProductsUpdate) defaults() {
	if _, ok := opu.mutation.UpdatedAt(); !ok {
		v := orderproducts.UpdateDefaultUpdatedAt()
		opu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (opu *OrderProductsUpdate) check() error {
	if v, ok := opu.mutation.Quantity(); ok {
		if err := orderproducts.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderProducts.quantity": %w`, err)}
		}
	}
	if opu.mutation.OrderCleared() && len(opu.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderProducts.order"`)
	}
	return nil
}

func (opu *OrderProductsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := opu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderproducts.Table, orderproducts.Columns, sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt))
	if ps := opu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := opu.mutation.Quantity(); ok {
		_spec.SetField(orderproducts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := opu.mutation.AddedQuantity(); ok {
		_spec.AddField(orderproducts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := opu.mutation.CreatedAt(); ok {
		_spec.SetField(orderproducts.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := opu.mutation.UpdatedAt(); ok {
		_spec.SetField(orderproducts.FieldUpdatedAt, field.TypeTime, value)
	}
	if opu.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproducts.OrderTable,
			Columns: []string{orderproducts.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := opu.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproducts.OrderTable,
			Columns: []string{orderproducts.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, opu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderproducts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	opu.mutation.done = true
	return n, nil
}

// OrderProductsUpdateOne is the builder for updating a single OrderProducts entity.
type OrderProductsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderProductsMutation
}

// SetQuantity sets the "quantity" field.
func (opuo *OrderProductsUpdateOne) SetQuantity(i int) *OrderProductsUpdateOne {
	opuo.mutation.ResetQuantity()
	opuo.mutation.SetQuantity(i)
	return opuo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (opuo *OrderProductsUpdateOne) SetNillableQuantity(i *int) *OrderProductsUpdateOne {
	if i != nil {
		opuo.SetQuantity(*i)
	}
	return opuo
}

// AddQuantity adds i to the "quantity" field.
func (opuo *OrderProductsUpdateOne) AddQuantity(i int) *OrderProductsUpdateOne {
	opuo.mutation.AddQuantity(i)
	return opuo
}

// SetCreatedAt sets the "created_at" field.
func (opuo *OrderProductsUpdateOne) SetCreatedAt(t time.Time) *OrderProductsUpdateOne {
	opuo.mutation.SetCreatedAt(t)
	return opuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (opuo *OrderProductsUpdateOne) SetNillableCreatedAt(t *time.Time) *OrderProductsUpdateOne {
	if t != nil {
		opuo.SetCreatedAt(*t)
	}
	return opuo
}

// SetUpdatedAt sets the "updated_at" field.
func (opuo *OrderProductsUpdateOne) SetUpdatedAt(t time.Time) *OrderProductsUpdateOne {
	opuo.mutation.SetUpdatedAt(t)
	return opuo
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (opuo *OrderProductsUpdateOne) SetOrderID(id int) *OrderProductsUpdateOne {
	opuo.mutation.SetOrderID(id)
	return opuo
}

// SetOrder sets the "order" edge to the Order entity.
func (opuo *OrderProductsUpdateOne) SetOrder(o *Order) *OrderProductsUpdateOne {
	return opuo.SetOrderID(o.ID)
}

// Mutation returns the OrderProductsMutation object of the builder.
func (opuo *OrderProductsUpdateOne) Mutation() *OrderProductsMutation {
	return opuo.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (opuo *OrderProductsUpdateOne) ClearOrder() *OrderProductsUpdateOne {
	opuo.mutation.ClearOrder()
	return opuo
}

// Where appends a list predicates to the OrderProductsUpdate builder.
func (opuo *OrderProductsUpdateOne) Where(ps ...predicate.OrderProducts) *OrderProductsUpdateOne {
	opuo.mutation.Where(ps...)
	return opuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (opuo *OrderProductsUpdateOne) Select(field string, fields ...string) *OrderProductsUpdateOne {
	opuo.fields = append([]string{field}, fields...)
	return opuo
}

// Save executes the query and returns the updated OrderProducts entity.
func (opuo *OrderProductsUpdateOne) Save(ctx context.Context) (*OrderProducts, error) {
	opuo.defaults()
	return withHooks(ctx, opuo.sqlSave, opuo.mutation, opuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (opuo *OrderProductsUpdateOne) SaveX(ctx context.Context) *OrderProducts {
	node, err := opuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (opuo *OrderProductsUpdateOne) Exec(ctx context.Context) error {
	_, err := opuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opuo *OrderProductsUpdateOne) ExecX(ctx context.Context) {
	if err := opuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (opuo *OrderProductsUpdateOne) defaults() {
	if _, ok := opuo.mutation.UpdatedAt(); !ok {
		v := orderproducts.UpdateDefaultUpdatedAt()
		opuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (opuo *OrderProductsUpdateOne) check() error {
	if v, ok := opuo.mutation.Quantity(); ok {
		if err := orderproducts.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderProducts.quantity": %w`, err)}
		}
	}
	if opuo.mutation.OrderCleared() && len(opuo.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderProducts.order"`)
	}
	return nil
}

func (opuo *OrderProductsUpdateOne) sqlSave(ctx context.Context) (_node *OrderProducts, err error) {
	if err := opuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderproducts.Table, orderproducts.Columns, sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt))
	id, ok := opuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderProducts.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := opuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderproducts.FieldID)
		for _, f := range fields {
			if !orderproducts.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderproducts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := opuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := opuo.mutation.Quantity(); ok {
		_spec.SetField(orderproducts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := opuo.mutation.AddedQuantity(); ok {
		_spec.AddField(orderproducts.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := opuo.mutation.CreatedAt(); ok {
		_spec.SetField(orderproducts.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := opuo.mutation.UpdatedAt(); ok {
		_spec.SetField(orderproducts.FieldUpdatedAt, field.TypeTime, value)
	}
	if opuo.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproducts.OrderTable,
			Columns: []string{orderproducts.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := opuo.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderproducts.OrderTable,
			Columns: []string{orderproducts.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderProducts{config: opuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, opuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderproducts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	opuo.mutation.done = true
	return _node, nil
}
