// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"golang-server/ent/order"
	"golang-server/ent/orderproducts"
	"golang-server/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderProductsQuery is the builder for querying OrderProducts entities.
type OrderProductsQuery struct {
	config
	ctx        *QueryContext
	order      []orderproducts.OrderOption
	inters     []Interceptor
	predicates []predicate.OrderProducts
	withOrder  *OrderQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderProductsQuery builder.
func (opq *OrderProductsQuery) Where(ps ...predicate.OrderProducts) *OrderProductsQuery {
	opq.predicates = append(opq.predicates, ps...)
	return opq
}

// Limit the number of records to be returned by this query.
func (opq *OrderProductsQuery) Limit(limit int) *OrderProductsQuery {
	opq.ctx.Limit = &limit
	return opq
}

// Offset to start from.
func (opq *OrderProductsQuery) Offset(offset int) *OrderProductsQuery {
	opq.ctx.Offset = &offset
	return opq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (opq *OrderProductsQuery) Unique(unique bool) *OrderProductsQuery {
	opq.ctx.Unique = &unique
	return opq
}

// Order specifies how the records should be ordered.
func (opq *OrderProductsQuery) Order(o ...orderproducts.OrderOption) *OrderProductsQuery {
	opq.order = append(opq.order, o...)
	return opq
}

// QueryOrder chains the current query on the "order" edge.
func (opq *OrderProductsQuery) QueryOrder() *OrderQuery {
	query := (&OrderClient{config: opq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := opq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := opq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderproducts.Table, orderproducts.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderproducts.OrderTable, orderproducts.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(opq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrderProducts entity from the query.
// Returns a *NotFoundError when no OrderProducts was found.
func (opq *OrderProductsQuery) First(ctx context.Context) (*OrderProducts, error) {
	nodes, err := opq.Limit(1).All(setContextOp(ctx, opq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orderproducts.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (opq *OrderProductsQuery) FirstX(ctx context.Context) *OrderProducts {
	node, err := opq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderProducts ID from the query.
// Returns a *NotFoundError when no OrderProducts ID was found.
func (opq *OrderProductsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = opq.Limit(1).IDs(setContextOp(ctx, opq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orderproducts.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (opq *OrderProductsQuery) FirstIDX(ctx context.Context) int {
	id, err := opq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderProducts entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderProducts entity is found.
// Returns a *NotFoundError when no OrderProducts entities are found.
func (opq *OrderProductsQuery) Only(ctx context.Context) (*OrderProducts, error) {
	nodes, err := opq.Limit(2).All(setContextOp(ctx, opq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orderproducts.Label}
	default:
		return nil, &NotSingularError{orderproducts.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (opq *OrderProductsQuery) OnlyX(ctx context.Context) *OrderProducts {
	node, err := opq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderProducts ID in the query.
// Returns a *NotSingularError when more than one OrderProducts ID is found.
// Returns a *NotFoundError when no entities are found.
func (opq *OrderProductsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = opq.Limit(2).IDs(setContextOp(ctx, opq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orderproducts.Label}
	default:
		err = &NotSingularError{orderproducts.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (opq *OrderProductsQuery) OnlyIDX(ctx context.Context) int {
	id, err := opq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderProductsSlice.
func (opq *OrderProductsQuery) All(ctx context.Context) ([]*OrderProducts, error) {
	ctx = setContextOp(ctx, opq.ctx, ent.OpQueryAll)
	if err := opq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrderProducts, *OrderProductsQuery]()
	return withInterceptors[[]*OrderProducts](ctx, opq, qr, opq.inters)
}

// AllX is like All, but panics if an error occurs.
func (opq *OrderProductsQuery) AllX(ctx context.Context) []*OrderProducts {
	nodes, err := opq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderProducts IDs.
func (opq *OrderProductsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if opq.ctx.Unique == nil && opq.path != nil {
		opq.Unique(true)
	}
	ctx = setContextOp(ctx, opq.ctx, ent.OpQueryIDs)
	if err = opq.Select(orderproducts.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (opq *OrderProductsQuery) IDsX(ctx context.Context) []int {
	ids, err := opq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (opq *OrderProductsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, opq.ctx, ent.OpQueryCount)
	if err := opq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, opq, querierCount[*OrderProductsQuery](), opq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (opq *OrderProductsQuery) CountX(ctx context.Context) int {
	count, err := opq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (opq *OrderProductsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, opq.ctx, ent.OpQueryExist)
	switch _, err := opq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (opq *OrderProductsQuery) ExistX(ctx context.Context) bool {
	exist, err := opq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderProductsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (opq *OrderProductsQuery) Clone() *OrderProductsQuery {
	if opq == nil {
		return nil
	}
	return &OrderProductsQuery{
		config:     opq.config,
		ctx:        opq.ctx.Clone(),
		order:      append([]orderproducts.OrderOption{}, opq.order...),
		inters:     append([]Interceptor{}, opq.inters...),
		predicates: append([]predicate.OrderProducts{}, opq.predicates...),
		withOrder:  opq.withOrder.Clone(),
		// clone intermediate query.
		sql:  opq.sql.Clone(),
		path: opq.path,
	}
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (opq *OrderProductsQuery) WithOrder(opts ...func(*OrderQuery)) *OrderProductsQuery {
	query := (&OrderClient{config: opq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	opq.withOrder = query
	return opq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderProducts.Query().
//		GroupBy(orderproducts.FieldQuantity).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (opq *OrderProductsQuery) GroupBy(field string, fields ...string) *OrderProductsGroupBy {
	opq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderProductsGroupBy{build: opq}
	grbuild.flds = &opq.ctx.Fields
	grbuild.label = orderproducts.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Quantity int `json:"quantity,omitempty"`
//	}
//
//	client.OrderProducts.Query().
//		Select(orderproducts.FieldQuantity).
//		Scan(ctx, &v)
func (opq *OrderProductsQuery) Select(fields ...string) *OrderProductsSelect {
	opq.ctx.Fields = append(opq.ctx.Fields, fields...)
	sbuild := &OrderProductsSelect{OrderProductsQuery: opq}
	sbuild.label = orderproducts.Label
	sbuild.flds, sbuild.scan = &opq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderProductsSelect configured with the given aggregations.
func (opq *OrderProductsQuery) Aggregate(fns ...AggregateFunc) *OrderProductsSelect {
	return opq.Select().Aggregate(fns...)
}

func (opq *OrderProductsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range opq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, opq); err != nil {
				return err
			}
		}
	}
	for _, f := range opq.ctx.Fields {
		if !orderproducts.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if opq.path != nil {
		prev, err := opq.path(ctx)
		if err != nil {
			return err
		}
		opq.sql = prev
	}
	return nil
}

func (opq *OrderProductsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderProducts, error) {
	var (
		nodes       = []*OrderProducts{}
		withFKs     = opq.withFKs
		_spec       = opq.querySpec()
		loadedTypes = [1]bool{
			opq.withOrder != nil,
		}
	)
	if opq.withOrder != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, orderproducts.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrderProducts).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrderProducts{config: opq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, opq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := opq.withOrder; query != nil {
		if err := opq.loadOrder(ctx, query, nodes, nil,
			func(n *OrderProducts, e *Order) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (opq *OrderProductsQuery) loadOrder(ctx context.Context, query *OrderQuery, nodes []*OrderProducts, init func(*OrderProducts), assign func(*OrderProducts, *Order)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrderProducts)
	for i := range nodes {
		if nodes[i].order_order_products == nil {
			continue
		}
		fk := *nodes[i].order_order_products
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(order.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_order_products" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (opq *OrderProductsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := opq.querySpec()
	_spec.Node.Columns = opq.ctx.Fields
	if len(opq.ctx.Fields) > 0 {
		_spec.Unique = opq.ctx.Unique != nil && *opq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, opq.driver, _spec)
}

func (opq *OrderProductsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orderproducts.Table, orderproducts.Columns, sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt))
	_spec.From = opq.sql
	if unique := opq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if opq.path != nil {
		_spec.Unique = true
	}
	if fields := opq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderproducts.FieldID)
		for i := range fields {
			if fields[i] != orderproducts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := opq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := opq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := opq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := opq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (opq *OrderProductsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(opq.driver.Dialect())
	t1 := builder.Table(orderproducts.Table)
	columns := opq.ctx.Fields
	if len(columns) == 0 {
		columns = orderproducts.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if opq.sql != nil {
		selector = opq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if opq.ctx.Unique != nil && *opq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range opq.predicates {
		p(selector)
	}
	for _, p := range opq.order {
		p(selector)
	}
	if offset := opq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := opq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderProductsGroupBy is the group-by builder for OrderProducts entities.
type OrderProductsGroupBy struct {
	selector
	build *OrderProductsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (opgb *OrderProductsGroupBy) Aggregate(fns ...AggregateFunc) *OrderProductsGroupBy {
	opgb.fns = append(opgb.fns, fns...)
	return opgb
}

// Scan applies the selector query and scans the result into the given value.
func (opgb *OrderProductsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, opgb.build.ctx, ent.OpQueryGroupBy)
	if err := opgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderProductsQuery, *OrderProductsGroupBy](ctx, opgb.build, opgb, opgb.build.inters, v)
}

func (opgb *OrderProductsGroupBy) sqlScan(ctx context.Context, root *OrderProductsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(opgb.fns))
	for _, fn := range opgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*opgb.flds)+len(opgb.fns))
		for _, f := range *opgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*opgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := opgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderProductsSelect is the builder for selecting fields of OrderProducts entities.
type OrderProductsSelect struct {
	*OrderProductsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ops *OrderProductsSelect) Aggregate(fns ...AggregateFunc) *OrderProductsSelect {
	ops.fns = append(ops.fns, fns...)
	return ops
}

// Scan applies the selector query and scans the result into the given value.
func (ops *OrderProductsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ops.ctx, ent.OpQuerySelect)
	if err := ops.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderProductsQuery, *OrderProductsSelect](ctx, ops.OrderProductsQuery, ops, ops.inters, v)
}

func (ops *OrderProductsSelect) sqlScan(ctx context.Context, root *OrderProductsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ops.fns))
	for _, fn := range ops.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ops.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ops.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
