// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-server/ent/orderproducts"
	"golang-server/ent/product"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (pc *ProductCreate) SetTitle(s string) *ProductCreate {
	pc.mutation.SetTitle(s)
	return pc
}

// SetDescription sets the "description" field.
func (pc *ProductCreate) SetDescription(s string) *ProductCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetCategory sets the "category" field.
func (pc *ProductCreate) SetCategory(s string) *ProductCreate {
	pc.mutation.SetCategory(s)
	return pc
}

// SetPrice sets the "price" field.
func (pc *ProductCreate) SetPrice(f float64) *ProductCreate {
	pc.mutation.SetPrice(f)
	return pc
}

// SetDiscountPercentage sets the "discount_percentage" field.
func (pc *ProductCreate) SetDiscountPercentage(f float64) *ProductCreate {
	pc.mutation.SetDiscountPercentage(f)
	return pc
}

// SetRating sets the "rating" field.
func (pc *ProductCreate) SetRating(f float64) *ProductCreate {
	pc.mutation.SetRating(f)
	return pc
}

// SetStock sets the "stock" field.
func (pc *ProductCreate) SetStock(i int) *ProductCreate {
	pc.mutation.SetStock(i)
	return pc
}

// SetBrand sets the "brand" field.
func (pc *ProductCreate) SetBrand(s string) *ProductCreate {
	pc.mutation.SetBrand(s)
	return pc
}

// SetSku sets the "sku" field.
func (pc *ProductCreate) SetSku(s string) *ProductCreate {
	pc.mutation.SetSku(s)
	return pc
}

// SetWeight sets the "weight" field.
func (pc *ProductCreate) SetWeight(f float64) *ProductCreate {
	pc.mutation.SetWeight(f)
	return pc
}

// SetWarrantyInformation sets the "warranty_information" field.
func (pc *ProductCreate) SetWarrantyInformation(s string) *ProductCreate {
	pc.mutation.SetWarrantyInformation(s)
	return pc
}

// SetShippingInformation sets the "shipping_information" field.
func (pc *ProductCreate) SetShippingInformation(s string) *ProductCreate {
	pc.mutation.SetShippingInformation(s)
	return pc
}

// SetAvailabilityStatus sets the "availability_status" field.
func (pc *ProductCreate) SetAvailabilityStatus(s string) *ProductCreate {
	pc.mutation.SetAvailabilityStatus(s)
	return pc
}

// SetReturnPolicy sets the "return_policy" field.
func (pc *ProductCreate) SetReturnPolicy(s string) *ProductCreate {
	pc.mutation.SetReturnPolicy(s)
	return pc
}

// SetMinimumOrderQuantity sets the "minimum_order_quantity" field.
func (pc *ProductCreate) SetMinimumOrderQuantity(i int) *ProductCreate {
	pc.mutation.SetMinimumOrderQuantity(i)
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *ProductCreate) SetCreatedAt(t time.Time) *ProductCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *ProductCreate) SetUpdatedAt(t time.Time) *ProductCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetBarcode sets the "barcode" field.
func (pc *ProductCreate) SetBarcode(s string) *ProductCreate {
	pc.mutation.SetBarcode(s)
	return pc
}

// SetQrCode sets the "qr_code" field.
func (pc *ProductCreate) SetQrCode(s string) *ProductCreate {
	pc.mutation.SetQrCode(s)
	return pc
}

// SetThumbnail sets the "thumbnail" field.
func (pc *ProductCreate) SetThumbnail(s string) *ProductCreate {
	pc.mutation.SetThumbnail(s)
	return pc
}

// SetTags sets the "tags" field.
func (pc *ProductCreate) SetTags(s []string) *ProductCreate {
	pc.mutation.SetTags(s)
	return pc
}

// SetImages sets the "images" field.
func (pc *ProductCreate) SetImages(s []string) *ProductCreate {
	pc.mutation.SetImages(s)
	return pc
}

// SetDimensions sets the "dimensions" field.
func (pc *ProductCreate) SetDimensions(m map[string]float64) *ProductCreate {
	pc.mutation.SetDimensions(m)
	return pc
}

// SetReviews sets the "reviews" field.
func (pc *ProductCreate) SetReviews(m []map[string]interface{}) *ProductCreate {
	pc.mutation.SetReviews(m)
	return pc
}

// AddOrderProductIDs adds the "order_products" edge to the OrderProducts entity by IDs.
func (pc *ProductCreate) AddOrderProductIDs(ids ...int) *ProductCreate {
	pc.mutation.AddOrderProductIDs(ids...)
	return pc
}

// AddOrderProducts adds the "order_products" edges to the OrderProducts entity.
func (pc *ProductCreate) AddOrderProducts(o ...*OrderProducts) *ProductCreate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pc.AddOrderProductIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (pc *ProductCreate) Mutation() *ProductMutation {
	return pc.mutation
}

// Save creates the Product in the database.
func (pc *ProductCreate) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProductCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProductCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProductCreate) check() error {
	if _, ok := pc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Product.title"`)}
	}
	if v, ok := pc.mutation.Title(); ok {
		if err := product.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Product.title": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Product.description"`)}
	}
	if v, ok := pc.mutation.Description(); ok {
		if err := product.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Product.description": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Product.category"`)}
	}
	if v, ok := pc.mutation.Category(); ok {
		if err := product.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Product.category": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Product.price"`)}
	}
	if _, ok := pc.mutation.DiscountPercentage(); !ok {
		return &ValidationError{Name: "discount_percentage", err: errors.New(`ent: missing required field "Product.discount_percentage"`)}
	}
	if _, ok := pc.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "Product.rating"`)}
	}
	if _, ok := pc.mutation.Stock(); !ok {
		return &ValidationError{Name: "stock", err: errors.New(`ent: missing required field "Product.stock"`)}
	}
	if _, ok := pc.mutation.Brand(); !ok {
		return &ValidationError{Name: "brand", err: errors.New(`ent: missing required field "Product.brand"`)}
	}
	if v, ok := pc.mutation.Brand(); ok {
		if err := product.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Product.brand": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Sku(); !ok {
		return &ValidationError{Name: "sku", err: errors.New(`ent: missing required field "Product.sku"`)}
	}
	if v, ok := pc.mutation.Sku(); ok {
		if err := product.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Product.sku": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "Product.weight"`)}
	}
	if _, ok := pc.mutation.WarrantyInformation(); !ok {
		return &ValidationError{Name: "warranty_information", err: errors.New(`ent: missing required field "Product.warranty_information"`)}
	}
	if v, ok := pc.mutation.WarrantyInformation(); ok {
		if err := product.WarrantyInformationValidator(v); err != nil {
			return &ValidationError{Name: "warranty_information", err: fmt.Errorf(`ent: validator failed for field "Product.warranty_information": %w`, err)}
		}
	}
	if _, ok := pc.mutation.ShippingInformation(); !ok {
		return &ValidationError{Name: "shipping_information", err: errors.New(`ent: missing required field "Product.shipping_information"`)}
	}
	if v, ok := pc.mutation.ShippingInformation(); ok {
		if err := product.ShippingInformationValidator(v); err != nil {
			return &ValidationError{Name: "shipping_information", err: fmt.Errorf(`ent: validator failed for field "Product.shipping_information": %w`, err)}
		}
	}
	if _, ok := pc.mutation.AvailabilityStatus(); !ok {
		return &ValidationError{Name: "availability_status", err: errors.New(`ent: missing required field "Product.availability_status"`)}
	}
	if v, ok := pc.mutation.AvailabilityStatus(); ok {
		if err := product.AvailabilityStatusValidator(v); err != nil {
			return &ValidationError{Name: "availability_status", err: fmt.Errorf(`ent: validator failed for field "Product.availability_status": %w`, err)}
		}
	}
	if _, ok := pc.mutation.ReturnPolicy(); !ok {
		return &ValidationError{Name: "return_policy", err: errors.New(`ent: missing required field "Product.return_policy"`)}
	}
	if v, ok := pc.mutation.ReturnPolicy(); ok {
		if err := product.ReturnPolicyValidator(v); err != nil {
			return &ValidationError{Name: "return_policy", err: fmt.Errorf(`ent: validator failed for field "Product.return_policy": %w`, err)}
		}
	}
	if _, ok := pc.mutation.MinimumOrderQuantity(); !ok {
		return &ValidationError{Name: "minimum_order_quantity", err: errors.New(`ent: missing required field "Product.minimum_order_quantity"`)}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Product.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Product.updated_at"`)}
	}
	if _, ok := pc.mutation.Barcode(); !ok {
		return &ValidationError{Name: "barcode", err: errors.New(`ent: missing required field "Product.barcode"`)}
	}
	if v, ok := pc.mutation.Barcode(); ok {
		if err := product.BarcodeValidator(v); err != nil {
			return &ValidationError{Name: "barcode", err: fmt.Errorf(`ent: validator failed for field "Product.barcode": %w`, err)}
		}
	}
	if _, ok := pc.mutation.QrCode(); !ok {
		return &ValidationError{Name: "qr_code", err: errors.New(`ent: missing required field "Product.qr_code"`)}
	}
	if v, ok := pc.mutation.QrCode(); ok {
		if err := product.QrCodeValidator(v); err != nil {
			return &ValidationError{Name: "qr_code", err: fmt.Errorf(`ent: validator failed for field "Product.qr_code": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Thumbnail(); !ok {
		return &ValidationError{Name: "thumbnail", err: errors.New(`ent: missing required field "Product.thumbnail"`)}
	}
	if v, ok := pc.mutation.Thumbnail(); ok {
		if err := product.ThumbnailValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail", err: fmt.Errorf(`ent: validator failed for field "Product.thumbnail": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Product.tags"`)}
	}
	if _, ok := pc.mutation.Images(); !ok {
		return &ValidationError{Name: "images", err: errors.New(`ent: missing required field "Product.images"`)}
	}
	if _, ok := pc.mutation.Dimensions(); !ok {
		return &ValidationError{Name: "dimensions", err: errors.New(`ent: missing required field "Product.dimensions"`)}
	}
	if _, ok := pc.mutation.Reviews(); !ok {
		return &ValidationError{Name: "reviews", err: errors.New(`ent: missing required field "Product.reviews"`)}
	}
	return nil
}

func (pc *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pc.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := pc.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := pc.mutation.DiscountPercentage(); ok {
		_spec.SetField(product.FieldDiscountPercentage, field.TypeFloat64, value)
		_node.DiscountPercentage = value
	}
	if value, ok := pc.mutation.Rating(); ok {
		_spec.SetField(product.FieldRating, field.TypeFloat64, value)
		_node.Rating = value
	}
	if value, ok := pc.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
		_node.Stock = value
	}
	if value, ok := pc.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
		_node.Brand = value
	}
	if value, ok := pc.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
		_node.Sku = value
	}
	if value, ok := pc.mutation.Weight(); ok {
		_spec.SetField(product.FieldWeight, field.TypeFloat64, value)
		_node.Weight = value
	}
	if value, ok := pc.mutation.WarrantyInformation(); ok {
		_spec.SetField(product.FieldWarrantyInformation, field.TypeString, value)
		_node.WarrantyInformation = value
	}
	if value, ok := pc.mutation.ShippingInformation(); ok {
		_spec.SetField(product.FieldShippingInformation, field.TypeString, value)
		_node.ShippingInformation = value
	}
	if value, ok := pc.mutation.AvailabilityStatus(); ok {
		_spec.SetField(product.FieldAvailabilityStatus, field.TypeString, value)
		_node.AvailabilityStatus = value
	}
	if value, ok := pc.mutation.ReturnPolicy(); ok {
		_spec.SetField(product.FieldReturnPolicy, field.TypeString, value)
		_node.ReturnPolicy = value
	}
	if value, ok := pc.mutation.MinimumOrderQuantity(); ok {
		_spec.SetField(product.FieldMinimumOrderQuantity, field.TypeInt, value)
		_node.MinimumOrderQuantity = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
		_node.Barcode = value
	}
	if value, ok := pc.mutation.QrCode(); ok {
		_spec.SetField(product.FieldQrCode, field.TypeString, value)
		_node.QrCode = value
	}
	if value, ok := pc.mutation.Thumbnail(); ok {
		_spec.SetField(product.FieldThumbnail, field.TypeString, value)
		_node.Thumbnail = value
	}
	if value, ok := pc.mutation.Tags(); ok {
		_spec.SetField(product.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := pc.mutation.Images(); ok {
		_spec.SetField(product.FieldImages, field.TypeJSON, value)
		_node.Images = value
	}
	if value, ok := pc.mutation.Dimensions(); ok {
		_spec.SetField(product.FieldDimensions, field.TypeJSON, value)
		_node.Dimensions = value
	}
	if value, ok := pc.mutation.Reviews(); ok {
		_spec.SetField(product.FieldReviews, field.TypeJSON, value)
		_node.Reviews = value
	}
	if nodes := pc.mutation.OrderProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrderProductsTable,
			Columns: []string{product.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	err      error
	builders []*ProductCreate
}

// Save creates the Product entities in the database.
func (pcb *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Product, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
