// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-server/ent/orderproducts"
	"golang-server/ent/predicate"
	"golang-server/ent/product"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (pu *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetTitle sets the "title" field.
func (pu *ProductUpdate) SetTitle(s string) *ProductUpdate {
	pu.mutation.SetTitle(s)
	return pu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableTitle(s *string) *ProductUpdate {
	if s != nil {
		pu.SetTitle(*s)
	}
	return pu
}

// SetDescription sets the "description" field.
func (pu *ProductUpdate) SetDescription(s string) *ProductUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDescription(s *string) *ProductUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// SetCategory sets the "category" field.
func (pu *ProductUpdate) SetCategory(s string) *ProductUpdate {
	pu.mutation.SetCategory(s)
	return pu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableCategory(s *string) *ProductUpdate {
	if s != nil {
		pu.SetCategory(*s)
	}
	return pu
}

// SetPrice sets the "price" field.
func (pu *ProductUpdate) SetPrice(f float64) *ProductUpdate {
	pu.mutation.ResetPrice()
	pu.mutation.SetPrice(f)
	return pu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillablePrice(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetPrice(*f)
	}
	return pu
}

// AddPrice adds f to the "price" field.
func (pu *ProductUpdate) AddPrice(f float64) *ProductUpdate {
	pu.mutation.AddPrice(f)
	return pu
}

// SetDiscountPercentage sets the "discount_percentage" field.
func (pu *ProductUpdate) SetDiscountPercentage(f float64) *ProductUpdate {
	pu.mutation.ResetDiscountPercentage()
	pu.mutation.SetDiscountPercentage(f)
	return pu
}

// SetNillableDiscountPercentage sets the "discount_percentage" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDiscountPercentage(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetDiscountPercentage(*f)
	}
	return pu
}

// AddDiscountPercentage adds f to the "discount_percentage" field.
func (pu *ProductUpdate) AddDiscountPercentage(f float64) *ProductUpdate {
	pu.mutation.AddDiscountPercentage(f)
	return pu
}

// SetRating sets the "rating" field.
func (pu *ProductUpdate) SetRating(f float64) *ProductUpdate {
	pu.mutation.ResetRating()
	pu.mutation.SetRating(f)
	return pu
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableRating(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetRating(*f)
	}
	return pu
}

// AddRating adds f to the "rating" field.
func (pu *ProductUpdate) AddRating(f float64) *ProductUpdate {
	pu.mutation.AddRating(f)
	return pu
}

// SetStock sets the "stock" field.
func (pu *ProductUpdate) SetStock(i int) *ProductUpdate {
	pu.mutation.ResetStock()
	pu.mutation.SetStock(i)
	return pu
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableStock(i *int) *ProductUpdate {
	if i != nil {
		pu.SetStock(*i)
	}
	return pu
}

// AddStock adds i to the "stock" field.
func (pu *ProductUpdate) AddStock(i int) *ProductUpdate {
	pu.mutation.AddStock(i)
	return pu
}

// SetBrand sets the "brand" field.
func (pu *ProductUpdate) SetBrand(s string) *ProductUpdate {
	pu.mutation.SetBrand(s)
	return pu
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableBrand(s *string) *ProductUpdate {
	if s != nil {
		pu.SetBrand(*s)
	}
	return pu
}

// SetSku sets the "sku" field.
func (pu *ProductUpdate) SetSku(s string) *ProductUpdate {
	pu.mutation.SetSku(s)
	return pu
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableSku(s *string) *ProductUpdate {
	if s != nil {
		pu.SetSku(*s)
	}
	return pu
}

// SetWeight sets the "weight" field.
func (pu *ProductUpdate) SetWeight(f float64) *ProductUpdate {
	pu.mutation.ResetWeight()
	pu.mutation.SetWeight(f)
	return pu
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableWeight(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetWeight(*f)
	}
	return pu
}

// AddWeight adds f to the "weight" field.
func (pu *ProductUpdate) AddWeight(f float64) *ProductUpdate {
	pu.mutation.AddWeight(f)
	return pu
}

// SetWarrantyInformation sets the "warranty_information" field.
func (pu *ProductUpdate) SetWarrantyInformation(s string) *ProductUpdate {
	pu.mutation.SetWarrantyInformation(s)
	return pu
}

// SetNillableWarrantyInformation sets the "warranty_information" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableWarrantyInformation(s *string) *ProductUpdate {
	if s != nil {
		pu.SetWarrantyInformation(*s)
	}
	return pu
}

// SetShippingInformation sets the "shipping_information" field.
func (pu *ProductUpdate) SetShippingInformation(s string) *ProductUpdate {
	pu.mutation.SetShippingInformation(s)
	return pu
}

// SetNillableShippingInformation sets the "shipping_information" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableShippingInformation(s *string) *ProductUpdate {
	if s != nil {
		pu.SetShippingInformation(*s)
	}
	return pu
}

// SetAvailabilityStatus sets the "availability_status" field.
func (pu *ProductUpdate) SetAvailabilityStatus(s string) *ProductUpdate {
	pu.mutation.SetAvailabilityStatus(s)
	return pu
}

// SetNillableAvailabilityStatus sets the "availability_status" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableAvailabilityStatus(s *string) *ProductUpdate {
	if s != nil {
		pu.SetAvailabilityStatus(*s)
	}
	return pu
}

// SetReturnPolicy sets the "return_policy" field.
func (pu *ProductUpdate) SetReturnPolicy(s string) *ProductUpdate {
	pu.mutation.SetReturnPolicy(s)
	return pu
}

// SetNillableReturnPolicy sets the "return_policy" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableReturnPolicy(s *string) *ProductUpdate {
	if s != nil {
		pu.SetReturnPolicy(*s)
	}
	return pu
}

// SetMinimumOrderQuantity sets the "minimum_order_quantity" field.
func (pu *ProductUpdate) SetMinimumOrderQuantity(i int) *ProductUpdate {
	pu.mutation.ResetMinimumOrderQuantity()
	pu.mutation.SetMinimumOrderQuantity(i)
	return pu
}

// SetNillableMinimumOrderQuantity sets the "minimum_order_quantity" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableMinimumOrderQuantity(i *int) *ProductUpdate {
	if i != nil {
		pu.SetMinimumOrderQuantity(*i)
	}
	return pu
}

// AddMinimumOrderQuantity adds i to the "minimum_order_quantity" field.
func (pu *ProductUpdate) AddMinimumOrderQuantity(i int) *ProductUpdate {
	pu.mutation.AddMinimumOrderQuantity(i)
	return pu
}

// SetCreatedAt sets the "created_at" field.
func (pu *ProductUpdate) SetCreatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetCreatedAt(t)
	return pu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableCreatedAt(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetCreatedAt(*t)
	}
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProductUpdate) SetUpdatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableUpdatedAt(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetUpdatedAt(*t)
	}
	return pu
}

// SetBarcode sets the "barcode" field.
func (pu *ProductUpdate) SetBarcode(s string) *ProductUpdate {
	pu.mutation.SetBarcode(s)
	return pu
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableBarcode(s *string) *ProductUpdate {
	if s != nil {
		pu.SetBarcode(*s)
	}
	return pu
}

// SetQrCode sets the "qr_code" field.
func (pu *ProductUpdate) SetQrCode(s string) *ProductUpdate {
	pu.mutation.SetQrCode(s)
	return pu
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableQrCode(s *string) *ProductUpdate {
	if s != nil {
		pu.SetQrCode(*s)
	}
	return pu
}

// SetThumbnail sets the "thumbnail" field.
func (pu *ProductUpdate) SetThumbnail(s string) *ProductUpdate {
	pu.mutation.SetThumbnail(s)
	return pu
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableThumbnail(s *string) *ProductUpdate {
	if s != nil {
		pu.SetThumbnail(*s)
	}
	return pu
}

// SetTags sets the "tags" field.
func (pu *ProductUpdate) SetTags(s []string) *ProductUpdate {
	pu.mutation.SetTags(s)
	return pu
}

// AppendTags appends s to the "tags" field.
func (pu *ProductUpdate) AppendTags(s []string) *ProductUpdate {
	pu.mutation.AppendTags(s)
	return pu
}

// SetImages sets the "images" field.
func (pu *ProductUpdate) SetImages(s []string) *ProductUpdate {
	pu.mutation.SetImages(s)
	return pu
}

// AppendImages appends s to the "images" field.
func (pu *ProductUpdate) AppendImages(s []string) *ProductUpdate {
	pu.mutation.AppendImages(s)
	return pu
}

// SetDimensions sets the "dimensions" field.
func (pu *ProductUpdate) SetDimensions(m map[string]float64) *ProductUpdate {
	pu.mutation.SetDimensions(m)
	return pu
}

// SetReviews sets the "reviews" field.
func (pu *ProductUpdate) SetReviews(m []map[string]interface{}) *ProductUpdate {
	pu.mutation.SetReviews(m)
	return pu
}

// AppendReviews appends m to the "reviews" field.
func (pu *ProductUpdate) AppendReviews(m []map[string]interface{}) *ProductUpdate {
	pu.mutation.AppendReviews(m)
	return pu
}

// AddOrderProductIDs adds the "order_products" edge to the OrderProducts entity by IDs.
func (pu *ProductUpdate) AddOrderProductIDs(ids ...int) *ProductUpdate {
	pu.mutation.AddOrderProductIDs(ids...)
	return pu
}

// AddOrderProducts adds the "order_products" edges to the OrderProducts entity.
func (pu *ProductUpdate) AddOrderProducts(o ...*OrderProducts) *ProductUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pu.AddOrderProductIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (pu *ProductUpdate) Mutation() *ProductMutation {
	return pu.mutation
}

// ClearOrderProducts clears all "order_products" edges to the OrderProducts entity.
func (pu *ProductUpdate) ClearOrderProducts() *ProductUpdate {
	pu.mutation.ClearOrderProducts()
	return pu
}

// RemoveOrderProductIDs removes the "order_products" edge to OrderProducts entities by IDs.
func (pu *ProductUpdate) RemoveOrderProductIDs(ids ...int) *ProductUpdate {
	pu.mutation.RemoveOrderProductIDs(ids...)
	return pu
}

// RemoveOrderProducts removes "order_products" edges to OrderProducts entities.
func (pu *ProductUpdate) RemoveOrderProducts(o ...*OrderProducts) *ProductUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return pu.RemoveOrderProductIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProductUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProductUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProductUpdate) check() error {
	if v, ok := pu.mutation.Title(); ok {
		if err := product.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Product.title": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Description(); ok {
		if err := product.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Product.description": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Category(); ok {
		if err := product.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Product.category": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Brand(); ok {
		if err := product.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Product.brand": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Sku(); ok {
		if err := product.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Product.sku": %w`, err)}
		}
	}
	if v, ok := pu.mutation.WarrantyInformation(); ok {
		if err := product.WarrantyInformationValidator(v); err != nil {
			return &ValidationError{Name: "warranty_information", err: fmt.Errorf(`ent: validator failed for field "Product.warranty_information": %w`, err)}
		}
	}
	if v, ok := pu.mutation.ShippingInformation(); ok {
		if err := product.ShippingInformationValidator(v); err != nil {
			return &ValidationError{Name: "shipping_information", err: fmt.Errorf(`ent: validator failed for field "Product.shipping_information": %w`, err)}
		}
	}
	if v, ok := pu.mutation.AvailabilityStatus(); ok {
		if err := product.AvailabilityStatusValidator(v); err != nil {
			return &ValidationError{Name: "availability_status", err: fmt.Errorf(`ent: validator failed for field "Product.availability_status": %w`, err)}
		}
	}
	if v, ok := pu.mutation.ReturnPolicy(); ok {
		if err := product.ReturnPolicyValidator(v); err != nil {
			return &ValidationError{Name: "return_policy", err: fmt.Errorf(`ent: validator failed for field "Product.return_policy": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Barcode(); ok {
		if err := product.BarcodeValidator(v); err != nil {
			return &ValidationError{Name: "barcode", err: fmt.Errorf(`ent: validator failed for field "Product.barcode": %w`, err)}
		}
	}
	if v, ok := pu.mutation.QrCode(); ok {
		if err := product.QrCodeValidator(v); err != nil {
			return &ValidationError{Name: "qr_code", err: fmt.Errorf(`ent: validator failed for field "Product.qr_code": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Thumbnail(); ok {
		if err := product.ThumbnailValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail", err: fmt.Errorf(`ent: validator failed for field "Product.thumbnail": %w`, err)}
		}
	}
	return nil
}

func (pu *ProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if value, ok := pu.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
	}
	if value, ok := pu.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.DiscountPercentage(); ok {
		_spec.SetField(product.FieldDiscountPercentage, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedDiscountPercentage(); ok {
		_spec.AddField(product.FieldDiscountPercentage, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.Rating(); ok {
		_spec.SetField(product.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedRating(); ok {
		_spec.AddField(product.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedStock(); ok {
		_spec.AddField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
	}
	if value, ok := pu.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
	}
	if value, ok := pu.mutation.Weight(); ok {
		_spec.SetField(product.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedWeight(); ok {
		_spec.AddField(product.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.WarrantyInformation(); ok {
		_spec.SetField(product.FieldWarrantyInformation, field.TypeString, value)
	}
	if value, ok := pu.mutation.ShippingInformation(); ok {
		_spec.SetField(product.FieldShippingInformation, field.TypeString, value)
	}
	if value, ok := pu.mutation.AvailabilityStatus(); ok {
		_spec.SetField(product.FieldAvailabilityStatus, field.TypeString, value)
	}
	if value, ok := pu.mutation.ReturnPolicy(); ok {
		_spec.SetField(product.FieldReturnPolicy, field.TypeString, value)
	}
	if value, ok := pu.mutation.MinimumOrderQuantity(); ok {
		_spec.SetField(product.FieldMinimumOrderQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedMinimumOrderQuantity(); ok {
		_spec.AddField(product.FieldMinimumOrderQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
	}
	if value, ok := pu.mutation.QrCode(); ok {
		_spec.SetField(product.FieldQrCode, field.TypeString, value)
	}
	if value, ok := pu.mutation.Thumbnail(); ok {
		_spec.SetField(product.FieldThumbnail, field.TypeString, value)
	}
	if value, ok := pu.mutation.Tags(); ok {
		_spec.SetField(product.FieldTags, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldTags, value)
		})
	}
	if value, ok := pu.mutation.Images(); ok {
		_spec.SetField(product.FieldImages, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldImages, value)
		})
	}
	if value, ok := pu.mutation.Dimensions(); ok {
		_spec.SetField(product.FieldDimensions, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.Reviews(); ok {
		_spec.SetField(product.FieldReviews, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedReviews(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldReviews, value)
		})
	}
	if pu.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrderProductsTable,
			Columns: []string{product.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedOrderProductsIDs(); len(nodes) > 0 && !pu.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrderProductsTable,
			Columns: []string{product.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.OrderProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrderProductsTable,
			Columns: []string{product.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetTitle sets the "title" field.
func (puo *ProductUpdateOne) SetTitle(s string) *ProductUpdateOne {
	puo.mutation.SetTitle(s)
	return puo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableTitle(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetTitle(*s)
	}
	return puo
}

// SetDescription sets the "description" field.
func (puo *ProductUpdateOne) SetDescription(s string) *ProductUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDescription(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// SetCategory sets the "category" field.
func (puo *ProductUpdateOne) SetCategory(s string) *ProductUpdateOne {
	puo.mutation.SetCategory(s)
	return puo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableCategory(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetCategory(*s)
	}
	return puo
}

// SetPrice sets the "price" field.
func (puo *ProductUpdateOne) SetPrice(f float64) *ProductUpdateOne {
	puo.mutation.ResetPrice()
	puo.mutation.SetPrice(f)
	return puo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillablePrice(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetPrice(*f)
	}
	return puo
}

// AddPrice adds f to the "price" field.
func (puo *ProductUpdateOne) AddPrice(f float64) *ProductUpdateOne {
	puo.mutation.AddPrice(f)
	return puo
}

// SetDiscountPercentage sets the "discount_percentage" field.
func (puo *ProductUpdateOne) SetDiscountPercentage(f float64) *ProductUpdateOne {
	puo.mutation.ResetDiscountPercentage()
	puo.mutation.SetDiscountPercentage(f)
	return puo
}

// SetNillableDiscountPercentage sets the "discount_percentage" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDiscountPercentage(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetDiscountPercentage(*f)
	}
	return puo
}

// AddDiscountPercentage adds f to the "discount_percentage" field.
func (puo *ProductUpdateOne) AddDiscountPercentage(f float64) *ProductUpdateOne {
	puo.mutation.AddDiscountPercentage(f)
	return puo
}

// SetRating sets the "rating" field.
func (puo *ProductUpdateOne) SetRating(f float64) *ProductUpdateOne {
	puo.mutation.ResetRating()
	puo.mutation.SetRating(f)
	return puo
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableRating(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetRating(*f)
	}
	return puo
}

// AddRating adds f to the "rating" field.
func (puo *ProductUpdateOne) AddRating(f float64) *ProductUpdateOne {
	puo.mutation.AddRating(f)
	return puo
}

// SetStock sets the "stock" field.
func (puo *ProductUpdateOne) SetStock(i int) *ProductUpdateOne {
	puo.mutation.ResetStock()
	puo.mutation.SetStock(i)
	return puo
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableStock(i *int) *ProductUpdateOne {
	if i != nil {
		puo.SetStock(*i)
	}
	return puo
}

// AddStock adds i to the "stock" field.
func (puo *ProductUpdateOne) AddStock(i int) *ProductUpdateOne {
	puo.mutation.AddStock(i)
	return puo
}

// SetBrand sets the "brand" field.
func (puo *ProductUpdateOne) SetBrand(s string) *ProductUpdateOne {
	puo.mutation.SetBrand(s)
	return puo
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableBrand(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetBrand(*s)
	}
	return puo
}

// SetSku sets the "sku" field.
func (puo *ProductUpdateOne) SetSku(s string) *ProductUpdateOne {
	puo.mutation.SetSku(s)
	return puo
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableSku(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetSku(*s)
	}
	return puo
}

// SetWeight sets the "weight" field.
func (puo *ProductUpdateOne) SetWeight(f float64) *ProductUpdateOne {
	puo.mutation.ResetWeight()
	puo.mutation.SetWeight(f)
	return puo
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableWeight(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetWeight(*f)
	}
	return puo
}

// AddWeight adds f to the "weight" field.
func (puo *ProductUpdateOne) AddWeight(f float64) *ProductUpdateOne {
	puo.mutation.AddWeight(f)
	return puo
}

// SetWarrantyInformation sets the "warranty_information" field.
func (puo *ProductUpdateOne) SetWarrantyInformation(s string) *ProductUpdateOne {
	puo.mutation.SetWarrantyInformation(s)
	return puo
}

// SetNillableWarrantyInformation sets the "warranty_information" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableWarrantyInformation(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetWarrantyInformation(*s)
	}
	return puo
}

// SetShippingInformation sets the "shipping_information" field.
func (puo *ProductUpdateOne) SetShippingInformation(s string) *ProductUpdateOne {
	puo.mutation.SetShippingInformation(s)
	return puo
}

// SetNillableShippingInformation sets the "shipping_information" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableShippingInformation(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetShippingInformation(*s)
	}
	return puo
}

// SetAvailabilityStatus sets the "availability_status" field.
func (puo *ProductUpdateOne) SetAvailabilityStatus(s string) *ProductUpdateOne {
	puo.mutation.SetAvailabilityStatus(s)
	return puo
}

// SetNillableAvailabilityStatus sets the "availability_status" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableAvailabilityStatus(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetAvailabilityStatus(*s)
	}
	return puo
}

// SetReturnPolicy sets the "return_policy" field.
func (puo *ProductUpdateOne) SetReturnPolicy(s string) *ProductUpdateOne {
	puo.mutation.SetReturnPolicy(s)
	return puo
}

// SetNillableReturnPolicy sets the "return_policy" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableReturnPolicy(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetReturnPolicy(*s)
	}
	return puo
}

// SetMinimumOrderQuantity sets the "minimum_order_quantity" field.
func (puo *ProductUpdateOne) SetMinimumOrderQuantity(i int) *ProductUpdateOne {
	puo.mutation.ResetMinimumOrderQuantity()
	puo.mutation.SetMinimumOrderQuantity(i)
	return puo
}

// SetNillableMinimumOrderQuantity sets the "minimum_order_quantity" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableMinimumOrderQuantity(i *int) *ProductUpdateOne {
	if i != nil {
		puo.SetMinimumOrderQuantity(*i)
	}
	return puo
}

// AddMinimumOrderQuantity adds i to the "minimum_order_quantity" field.
func (puo *ProductUpdateOne) AddMinimumOrderQuantity(i int) *ProductUpdateOne {
	puo.mutation.AddMinimumOrderQuantity(i)
	return puo
}

// SetCreatedAt sets the "created_at" field.
func (puo *ProductUpdateOne) SetCreatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetCreatedAt(t)
	return puo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableCreatedAt(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetCreatedAt(*t)
	}
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProductUpdateOne) SetUpdatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableUpdatedAt(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetUpdatedAt(*t)
	}
	return puo
}

// SetBarcode sets the "barcode" field.
func (puo *ProductUpdateOne) SetBarcode(s string) *ProductUpdateOne {
	puo.mutation.SetBarcode(s)
	return puo
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableBarcode(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetBarcode(*s)
	}
	return puo
}

// SetQrCode sets the "qr_code" field.
func (puo *ProductUpdateOne) SetQrCode(s string) *ProductUpdateOne {
	puo.mutation.SetQrCode(s)
	return puo
}

// SetNillableQrCode sets the "qr_code" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableQrCode(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetQrCode(*s)
	}
	return puo
}

// SetThumbnail sets the "thumbnail" field.
func (puo *ProductUpdateOne) SetThumbnail(s string) *ProductUpdateOne {
	puo.mutation.SetThumbnail(s)
	return puo
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableThumbnail(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetThumbnail(*s)
	}
	return puo
}

// SetTags sets the "tags" field.
func (puo *ProductUpdateOne) SetTags(s []string) *ProductUpdateOne {
	puo.mutation.SetTags(s)
	return puo
}

// AppendTags appends s to the "tags" field.
func (puo *ProductUpdateOne) AppendTags(s []string) *ProductUpdateOne {
	puo.mutation.AppendTags(s)
	return puo
}

// SetImages sets the "images" field.
func (puo *ProductUpdateOne) SetImages(s []string) *ProductUpdateOne {
	puo.mutation.SetImages(s)
	return puo
}

// AppendImages appends s to the "images" field.
func (puo *ProductUpdateOne) AppendImages(s []string) *ProductUpdateOne {
	puo.mutation.AppendImages(s)
	return puo
}

// SetDimensions sets the "dimensions" field.
func (puo *ProductUpdateOne) SetDimensions(m map[string]float64) *ProductUpdateOne {
	puo.mutation.SetDimensions(m)
	return puo
}

// SetReviews sets the "reviews" field.
func (puo *ProductUpdateOne) SetReviews(m []map[string]interface{}) *ProductUpdateOne {
	puo.mutation.SetReviews(m)
	return puo
}

// AppendReviews appends m to the "reviews" field.
func (puo *ProductUpdateOne) AppendReviews(m []map[string]interface{}) *ProductUpdateOne {
	puo.mutation.AppendReviews(m)
	return puo
}

// AddOrderProductIDs adds the "order_products" edge to the OrderProducts entity by IDs.
func (puo *ProductUpdateOne) AddOrderProductIDs(ids ...int) *ProductUpdateOne {
	puo.mutation.AddOrderProductIDs(ids...)
	return puo
}

// AddOrderProducts adds the "order_products" edges to the OrderProducts entity.
func (puo *ProductUpdateOne) AddOrderProducts(o ...*OrderProducts) *ProductUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return puo.AddOrderProductIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (puo *ProductUpdateOne) Mutation() *ProductMutation {
	return puo.mutation
}

// ClearOrderProducts clears all "order_products" edges to the OrderProducts entity.
func (puo *ProductUpdateOne) ClearOrderProducts() *ProductUpdateOne {
	puo.mutation.ClearOrderProducts()
	return puo
}

// RemoveOrderProductIDs removes the "order_products" edge to OrderProducts entities by IDs.
func (puo *ProductUpdateOne) RemoveOrderProductIDs(ids ...int) *ProductUpdateOne {
	puo.mutation.RemoveOrderProductIDs(ids...)
	return puo
}

// RemoveOrderProducts removes "order_products" edges to OrderProducts entities.
func (puo *ProductUpdateOne) RemoveOrderProducts(o ...*OrderProducts) *ProductUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return puo.RemoveOrderProductIDs(ids...)
}

// Where appends a list predicates to the ProductUpdate builder.
func (puo *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Product entity.
func (puo *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProductUpdateOne) check() error {
	if v, ok := puo.mutation.Title(); ok {
		if err := product.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Product.title": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Description(); ok {
		if err := product.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Product.description": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Category(); ok {
		if err := product.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Product.category": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Brand(); ok {
		if err := product.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Product.brand": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Sku(); ok {
		if err := product.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Product.sku": %w`, err)}
		}
	}
	if v, ok := puo.mutation.WarrantyInformation(); ok {
		if err := product.WarrantyInformationValidator(v); err != nil {
			return &ValidationError{Name: "warranty_information", err: fmt.Errorf(`ent: validator failed for field "Product.warranty_information": %w`, err)}
		}
	}
	if v, ok := puo.mutation.ShippingInformation(); ok {
		if err := product.ShippingInformationValidator(v); err != nil {
			return &ValidationError{Name: "shipping_information", err: fmt.Errorf(`ent: validator failed for field "Product.shipping_information": %w`, err)}
		}
	}
	if v, ok := puo.mutation.AvailabilityStatus(); ok {
		if err := product.AvailabilityStatusValidator(v); err != nil {
			return &ValidationError{Name: "availability_status", err: fmt.Errorf(`ent: validator failed for field "Product.availability_status": %w`, err)}
		}
	}
	if v, ok := puo.mutation.ReturnPolicy(); ok {
		if err := product.ReturnPolicyValidator(v); err != nil {
			return &ValidationError{Name: "return_policy", err: fmt.Errorf(`ent: validator failed for field "Product.return_policy": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Barcode(); ok {
		if err := product.BarcodeValidator(v); err != nil {
			return &ValidationError{Name: "barcode", err: fmt.Errorf(`ent: validator failed for field "Product.barcode": %w`, err)}
		}
	}
	if v, ok := puo.mutation.QrCode(); ok {
		if err := product.QrCodeValidator(v); err != nil {
			return &ValidationError{Name: "qr_code", err: fmt.Errorf(`ent: validator failed for field "Product.qr_code": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Thumbnail(); ok {
		if err := product.ThumbnailValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail", err: fmt.Errorf(`ent: validator failed for field "Product.thumbnail": %w`, err)}
		}
	}
	return nil
}

func (puo *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if value, ok := puo.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
	}
	if value, ok := puo.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedPrice(); ok {
		_spec.AddField(product.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.DiscountPercentage(); ok {
		_spec.SetField(product.FieldDiscountPercentage, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedDiscountPercentage(); ok {
		_spec.AddField(product.FieldDiscountPercentage, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.Rating(); ok {
		_spec.SetField(product.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedRating(); ok {
		_spec.AddField(product.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedStock(); ok {
		_spec.AddField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
	}
	if value, ok := puo.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
	}
	if value, ok := puo.mutation.Weight(); ok {
		_spec.SetField(product.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedWeight(); ok {
		_spec.AddField(product.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.WarrantyInformation(); ok {
		_spec.SetField(product.FieldWarrantyInformation, field.TypeString, value)
	}
	if value, ok := puo.mutation.ShippingInformation(); ok {
		_spec.SetField(product.FieldShippingInformation, field.TypeString, value)
	}
	if value, ok := puo.mutation.AvailabilityStatus(); ok {
		_spec.SetField(product.FieldAvailabilityStatus, field.TypeString, value)
	}
	if value, ok := puo.mutation.ReturnPolicy(); ok {
		_spec.SetField(product.FieldReturnPolicy, field.TypeString, value)
	}
	if value, ok := puo.mutation.MinimumOrderQuantity(); ok {
		_spec.SetField(product.FieldMinimumOrderQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedMinimumOrderQuantity(); ok {
		_spec.AddField(product.FieldMinimumOrderQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
	}
	if value, ok := puo.mutation.QrCode(); ok {
		_spec.SetField(product.FieldQrCode, field.TypeString, value)
	}
	if value, ok := puo.mutation.Thumbnail(); ok {
		_spec.SetField(product.FieldThumbnail, field.TypeString, value)
	}
	if value, ok := puo.mutation.Tags(); ok {
		_spec.SetField(product.FieldTags, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldTags, value)
		})
	}
	if value, ok := puo.mutation.Images(); ok {
		_spec.SetField(product.FieldImages, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldImages, value)
		})
	}
	if value, ok := puo.mutation.Dimensions(); ok {
		_spec.SetField(product.FieldDimensions, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.Reviews(); ok {
		_spec.SetField(product.FieldReviews, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedReviews(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldReviews, value)
		})
	}
	if puo.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrderProductsTable,
			Columns: []string{product.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedOrderProductsIDs(); len(nodes) > 0 && !puo.mutation.OrderProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrderProductsTable,
			Columns: []string{product.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.OrderProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.OrderProductsTable,
			Columns: []string{product.OrderProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderproducts.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Product{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
