// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"golang-server/ent/product"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Product is the model entity for the Product schema.
type Product struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// DiscountPercentage holds the value of the "discount_percentage" field.
	DiscountPercentage float64 `json:"discount_percentage,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating float64 `json:"rating,omitempty"`
	// Stock holds the value of the "stock" field.
	Stock int `json:"stock,omitempty"`
	// Brand holds the value of the "brand" field.
	Brand string `json:"brand,omitempty"`
	// Sku holds the value of the "sku" field.
	Sku string `json:"sku,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight float64 `json:"weight,omitempty"`
	// WarrantyInformation holds the value of the "warranty_information" field.
	WarrantyInformation string `json:"warranty_information,omitempty"`
	// ShippingInformation holds the value of the "shipping_information" field.
	ShippingInformation string `json:"shipping_information,omitempty"`
	// AvailabilityStatus holds the value of the "availability_status" field.
	AvailabilityStatus string `json:"availability_status,omitempty"`
	// ReturnPolicy holds the value of the "return_policy" field.
	ReturnPolicy string `json:"return_policy,omitempty"`
	// MinimumOrderQuantity holds the value of the "minimum_order_quantity" field.
	MinimumOrderQuantity int `json:"minimum_order_quantity,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Barcode holds the value of the "barcode" field.
	Barcode string `json:"barcode,omitempty"`
	// QrCode holds the value of the "qr_code" field.
	QrCode string `json:"qr_code,omitempty"`
	// Thumbnail holds the value of the "thumbnail" field.
	Thumbnail string `json:"thumbnail,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// Images holds the value of the "images" field.
	Images []string `json:"images,omitempty"`
	// Dimensions holds the value of the "dimensions" field.
	Dimensions map[string]float64 `json:"dimensions,omitempty"`
	// Reviews holds the value of the "reviews" field.
	Reviews []map[string]interface{} `json:"reviews,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductQuery when eager-loading is set.
	Edges        ProductEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductEdges holds the relations/edges for other nodes in the graph.
type ProductEdges struct {
	// OrderProducts holds the value of the order_products edge.
	OrderProducts []*OrderProducts `json:"order_products,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OrderProductsOrErr returns the OrderProducts value or an error if the edge
// was not loaded in eager-loading.
func (e ProductEdges) OrderProductsOrErr() ([]*OrderProducts, error) {
	if e.loadedTypes[0] {
		return e.OrderProducts, nil
	}
	return nil, &NotLoadedError{edge: "order_products"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Product) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case product.FieldTags, product.FieldImages, product.FieldDimensions, product.FieldReviews:
			values[i] = new([]byte)
		case product.FieldPrice, product.FieldDiscountPercentage, product.FieldRating, product.FieldWeight:
			values[i] = new(sql.NullFloat64)
		case product.FieldID, product.FieldStock, product.FieldMinimumOrderQuantity:
			values[i] = new(sql.NullInt64)
		case product.FieldTitle, product.FieldDescription, product.FieldCategory, product.FieldBrand, product.FieldSku, product.FieldWarrantyInformation, product.FieldShippingInformation, product.FieldAvailabilityStatus, product.FieldReturnPolicy, product.FieldBarcode, product.FieldQrCode, product.FieldThumbnail:
			values[i] = new(sql.NullString)
		case product.FieldCreatedAt, product.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Product fields.
func (pr *Product) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case product.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case product.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				pr.Title = value.String
			}
		case product.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				pr.Description = value.String
			}
		case product.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				pr.Category = value.String
			}
		case product.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				pr.Price = value.Float64
			}
		case product.FieldDiscountPercentage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_percentage", values[i])
			} else if value.Valid {
				pr.DiscountPercentage = value.Float64
			}
		case product.FieldRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				pr.Rating = value.Float64
			}
		case product.FieldStock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stock", values[i])
			} else if value.Valid {
				pr.Stock = int(value.Int64)
			}
		case product.FieldBrand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field brand", values[i])
			} else if value.Valid {
				pr.Brand = value.String
			}
		case product.FieldSku:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku", values[i])
			} else if value.Valid {
				pr.Sku = value.String
			}
		case product.FieldWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				pr.Weight = value.Float64
			}
		case product.FieldWarrantyInformation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field warranty_information", values[i])
			} else if value.Valid {
				pr.WarrantyInformation = value.String
			}
		case product.FieldShippingInformation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shipping_information", values[i])
			} else if value.Valid {
				pr.ShippingInformation = value.String
			}
		case product.FieldAvailabilityStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field availability_status", values[i])
			} else if value.Valid {
				pr.AvailabilityStatus = value.String
			}
		case product.FieldReturnPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field return_policy", values[i])
			} else if value.Valid {
				pr.ReturnPolicy = value.String
			}
		case product.FieldMinimumOrderQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field minimum_order_quantity", values[i])
			} else if value.Valid {
				pr.MinimumOrderQuantity = int(value.Int64)
			}
		case product.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pr.CreatedAt = value.Time
			}
		case product.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pr.UpdatedAt = value.Time
			}
		case product.FieldBarcode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field barcode", values[i])
			} else if value.Valid {
				pr.Barcode = value.String
			}
		case product.FieldQrCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_code", values[i])
			} else if value.Valid {
				pr.QrCode = value.String
			}
		case product.FieldThumbnail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail", values[i])
			} else if value.Valid {
				pr.Thumbnail = value.String
			}
		case product.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pr.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case product.FieldImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pr.Images); err != nil {
					return fmt.Errorf("unmarshal field images: %w", err)
				}
			}
		case product.FieldDimensions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dimensions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pr.Dimensions); err != nil {
					return fmt.Errorf("unmarshal field dimensions: %w", err)
				}
			}
		case product.FieldReviews:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reviews", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pr.Reviews); err != nil {
					return fmt.Errorf("unmarshal field reviews: %w", err)
				}
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Product.
// This includes values selected through modifiers, order, etc.
func (pr *Product) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryOrderProducts queries the "order_products" edge of the Product entity.
func (pr *Product) QueryOrderProducts() *OrderProductsQuery {
	return NewProductClient(pr.config).QueryOrderProducts(pr)
}

// Update returns a builder for updating this Product.
// Note that you need to call Product.Unwrap() before calling this method if this Product
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Product) Update() *ProductUpdateOne {
	return NewProductClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Product entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Product) Unwrap() *Product {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Product is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Product) String() string {
	var builder strings.Builder
	builder.WriteString("Product(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("title=")
	builder.WriteString(pr.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(pr.Description)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(pr.Category)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", pr.Price))
	builder.WriteString(", ")
	builder.WriteString("discount_percentage=")
	builder.WriteString(fmt.Sprintf("%v", pr.DiscountPercentage))
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", pr.Rating))
	builder.WriteString(", ")
	builder.WriteString("stock=")
	builder.WriteString(fmt.Sprintf("%v", pr.Stock))
	builder.WriteString(", ")
	builder.WriteString("brand=")
	builder.WriteString(pr.Brand)
	builder.WriteString(", ")
	builder.WriteString("sku=")
	builder.WriteString(pr.Sku)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", pr.Weight))
	builder.WriteString(", ")
	builder.WriteString("warranty_information=")
	builder.WriteString(pr.WarrantyInformation)
	builder.WriteString(", ")
	builder.WriteString("shipping_information=")
	builder.WriteString(pr.ShippingInformation)
	builder.WriteString(", ")
	builder.WriteString("availability_status=")
	builder.WriteString(pr.AvailabilityStatus)
	builder.WriteString(", ")
	builder.WriteString("return_policy=")
	builder.WriteString(pr.ReturnPolicy)
	builder.WriteString(", ")
	builder.WriteString("minimum_order_quantity=")
	builder.WriteString(fmt.Sprintf("%v", pr.MinimumOrderQuantity))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pr.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("barcode=")
	builder.WriteString(pr.Barcode)
	builder.WriteString(", ")
	builder.WriteString("qr_code=")
	builder.WriteString(pr.QrCode)
	builder.WriteString(", ")
	builder.WriteString("thumbnail=")
	builder.WriteString(pr.Thumbnail)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", pr.Tags))
	builder.WriteString(", ")
	builder.WriteString("images=")
	builder.WriteString(fmt.Sprintf("%v", pr.Images))
	builder.WriteString(", ")
	builder.WriteString("dimensions=")
	builder.WriteString(fmt.Sprintf("%v", pr.Dimensions))
	builder.WriteString(", ")
	builder.WriteString("reviews=")
	builder.WriteString(fmt.Sprintf("%v", pr.Reviews))
	builder.WriteByte(')')
	return builder.String()
}

// Products is a parsable slice of Product.
type Products []*Product
