// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Basket is the predicate function for basket builders.
type Basket func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderProducts is the predicate function for orderproducts builders.
type OrderProducts func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
